### ISSUE TITLE
Minor Request: Typescript typings support

### ISSUE THREAD

**Issue by lolzcalvin** [automerge/automerge#105]
As per the title. I was a little taken aback seeing that this such a good package has no typings yet. Though,  this is just a very minor request that doesn't really cause any issue for now.

**Comment by ept** [comment]
Hi @lolzcalvin, this seems like a good idea. However, I don't any of the Automerge maintainers have TypeScript experience. It would therefore be great if you could contribute it, if you have the time. Thanks!

**Comment by ept** [comment]
Here is one possible TypeScript type definition for Automerge, taken from a project that builds upon it:
https://github.com/inkandswitch/capstone/blob/master/src/types/automerge.d.ts

However, there is still some room for debate as to what a good type definition should look like. Due to the fact that Automerge's JSON-like data model is inherently dynamically-typed, the answer is not immediately obvious.

**Comment by j-f1** [comment]
The doc could have a type parameter specifying its contents.

**Comment by pvh** [comment]
@j-f1 Do you mean something different from the type parameter in the example above?

**Comment by j-f1** [comment]
Nope.

**Comment by drdgvhbh** [comment]
As a developer, its very difficult to figure out the functions on a certain object because logging to console will simply spit out a proxy object. Adding real typings would avoid this issue.
