### ISSUE TITLE
Configuring initial object on init()

### ISSUE THREAD

**Issue by samjohnduke** [automerge/automerge#127]
Hi, 

Just getting started with learning about automerge and I am creating an exploratory application to have a go. 

I was looking at the documentation and it seem fairly straight forward but i was wondering if it makes sense to have a non empty root document when calling init. I would like to be able to say that my document conforms to a particular object (say {nodes: []}). 

Is this something that you think might be a good idea / even possible? 

Sam

**Comment by pvh** [comment]
That sounds like a nice bit of syntactic sugar but I don't think needs any kind of special semantics. Would you agree?

**Comment by HerbCaudill** [comment]
I'd also like to be able to initialize an automerge document with something other than `{}`. Currently you have to do this: 

```js
let state = Automerge.init()
state = Automerge.change(state, d => d.todos=[])
state = Automerge.change(state, d=> d.filter='ALL')
```

This would be a lot more readable:

```js
const initialState = {
  todos: [],
  filter: 'ALL',
}
let state = Automerge.init({initialState})
```

or even

```js
let state = Automerge.from({
  todos: [],
  filter: 'ALL',
})
```

I started to try to implement this, but didn't get very far - I think I need to understand a bit more of the internals. @pvh or @ept - any pointers you could provide to get me going in the right direction would be appreciated.

**Comment by ept** [comment]
You can do this to set the initial state:

```js
let state = Automerge.change(Automerge.init(), doc => Object.assign(doc, initialState))
```

We could certainly consider adding a function `Automerge.from` that wraps up this pattern, e.g.:

```js
function from(initState) {
  return Automerge.change(Automerge.init(), doc => Object.assign(doc, initState))
}
```

…though I am not totally convinced that this one-liner is really worth adding.

There is also a deeper problem with initialisation that is discussed in [issue #4](https://github.com/automerge/automerge/issues/4#issuecomment-489569722): that is, initialisation does not happen only when a document is first created with `Automerge.init()`, but also at later points in its lifetime (e.g. when a new feature is added to the application, and that feature needs to initialize an empty object in the document to store its data). And that is the actual tricky issue. Initialisation on `Automerge.init()` is the easy bit.

**Comment by HerbCaudill** [comment]
@ept I'll submit a PR. I think that little bit of sugar would make a big difference! In practice that's something that you have to do over and over again (I'm currently using an `automergify` function all over the place). The empty state you get back from `init` is almost never of any practical value on its own, before it's been populated; and in cases where I do want an empty object, I end up saying `automergify({})` just to be clear.

In Typescript land, using `Automerge.from` would also have the advantage of skipping over the awkward state in between initialization and population, where rather than `<T>` you're technically dealing with `Partial<T>`:

https://github.com/automerge/automerge/blob/8c9b503781b7cb4aaeb89f0378a8bbc05edd6624/test/typescript_test.ts#L33-L40

**Comment by ept** [comment]
Okay, that makes sense. Thank you for the PR, I've merged it.
