### ISSUE TITLE
add and conflict handling function

### ISSUE THREAD

**Issue by mccoysc** [automerge/automerge#133]
maybe,autoMerge.applyChanges should be signature like the following:
autoMerge.applyChanges(oldDoc,changes,cb,userContext)

and when conflicted,the automerge call function 'cb', function 'cb' return the chosen result as the final result.
the cb's signature like the following:

function onConflict(value1,value2,userContext)

**Comment by mccoysc** [comment]
and the userContext is user-defined data and just only give the cb directly without any handle by automerge

**Comment by pvh** [comment]
Thanks for the suggestion, @mccoysc. Generally speaking, the goal of automerge is to provide a the same output for the same input at all nodes. That means that unless the callback could be guaranteed to be the same at all clients we could wind up with inconsistency.

Imagine the following situation: 
 - two users are picking a day for a meeting with Alice picking Monday and Bob picking Tuesday
 - Alice has a callback installed which resolved the conflict by choosing the value Monday
 - Bob has a callback installed which resolved the conflict by choosing the value Tuesday
 - Both go to a different meeting date even though they have up-to-date data!

I think the interface for detecting and responding to conflicts could definitely be improved but I'm not sure whether your current proposal is the right design.

**Comment by mccoysc** [comment]
i think it's not so reasonable.
now we know if conflicted,a random value would be returned by automerge.
'random' is not so reasonable,and which value should be returned is the user's responsibility.
and also,the _conflict field shoul be kept in this usage design.
@pvh

**Comment by pvh** [comment]
It's important to note that the currently selected value is not *random*, but *arbitrary*. A random value would be different at each node, an arbitrary value is the same at each node.

Still, @ept I wonder if I can extrapolate from @mccoysc's feedback a little. A callback that resolves the value might not be advisable, but perhaps we could benefit from a more discoverable mechanism for detecting if/when conflicts occur and surfacing them for user evaluation?

@mccoysc a really specific description of your problem would definitely be helpful. Something along the lines of: "I have an application where users are creating music playlists and when two users edit playlist metadata at the same time I'm concerned that one of their inputs will be lost. The current implementation means that anywhere I read values I also have to track the _conflicts field and that makes my code unreadable/complicated for a rarely-encountered exception. Here's a snippet of what that looks like."

Bonus points for "here's how I imagine the same code would be improved if you made the API change I suggest".

**Comment by mccoysc** [comment]
not "random" in fact,in the other words,it's to say that automerge supply a default conflict handle callback function.
maybe,the "default conflict handle function" is not suitable for my business or application.
and others thing,if i use the automerge.Connection, i have no chance to handle and track the conflicts.

**Comment by ept** [comment]
Hi @mccoysc, if you want completely custom conflict handling, perhaps a different datastore, such as [PouchDB](https://pouchdb.com/), will be better suited for you. Automerge is built on the principle of automatic merging (hence the name), and while there is scope for some application-specific logic, I would need to hear more about your application and the problems you are trying to solve, before jumping to solutions.

@pvh Better discoverability of conflicts (and indeed changes in general) would be good. I am thinking it would be nice to be able to hook into the stream of patches that goes from the backend to the frontend; observing patches would also make it easy to observe conflicts (since a patch that introduces a conflict indicates that fact explicitly). Do you have suggestions for an API? Registering a callback function feels a bit counter to the immutable nature of the API.

**Comment by arlair** [comment]
I was reading your documentation and when I read it randomly resolves the conflict, it made me think of the Gun database.

It uses string comparison to resolve as described more at: https://gun.eco/explainers/conflict/lexical.html
 
> So why string comparison? Because when merge conflicts happen, it’s critical that everyone agrees on a value, otherwise your database will never reach a consistent state, and any hope of accuracy goes out the window. String comparison guarantees that every merge conflict always has a clear winner.

**Comment by ept** [comment]
@arlair Automerge also picks a winner based on lexicographic ordering of actor IDs. It is sometimes called random because the actor IDs are chosen randomly (by default), but in fact it is deterministic for a given set of actor IDs. Moreover, Automerge does not throw away the concurrently written values, but rather keeps them for the application to inspect if desired.

However, I think the [example in the Gun documentation](https://gun.eco/explainers/conflict/lexical.html) (allocating seats at a concert) is a poor one. If people can ensure they win the seat selection lottery by setting their username to `'000000'`, they will surely do that. Hence the lexicographic conflict resolution does not make sense in a competitive situation. Automerge is designed for situations where the participants are collaborating, not competing.

**Comment by RahulBadenkal** [comment]
Hi, @ept . 
Is it still not possible to pass a custom callback that handles conflicts? 
My scenario:
`
myDoc = {
  KeyA: someValueA,
  ....,
  KeyCustom: {
    someKey: someVal,
    ...,
    servertimestamp: 27282829272
  }
}
`
Each peer has a button on the ui, By clicking on it server provides the value for KeyCustom via an api call.
What I want to do is show the latest data of KeyCustom amongst all the peers. So if user A clicks on the button with servertimestamp of the response t1 and user B clicks on the button with value t2 (t2> t1), I would always want to assign KeyCustom the object with the latest servertimestamp so that all users see the same (latest) data. How can I do that without providing a custom conflict handler?
Only solution I can think of is keep KeyCustom object seperate from automerge and and handle it but it would be nice to keep it all under the same main myDoc object.
Any ideas on how I can solve this issue?

**Comment by pvh** [comment]
Hi Rahul, the short answer is that Automerge's conflict resolution is not something you can customize. 

You can, of course, examine the history and perform another change() to select a different result than the one you have, or you could model the problem differently. For example, each peer could write a value to a field in a map or push a "bid" into an array with a timestamp and the server could choose whichever result it likes. 

On the other hand, if you have a single centralized server authority perhaps storing this value in a CRDT is not as useful. You could consider simply sending the data out of band or making an API call for this particular value.

Good luck!
