### ISSUE TITLE
apply changes error

### ISSUE THREAD

**Issue by mccoysc** [automerge/automerge#136]
var tmpDoc=Automerge.change(Automerge.init(),function(doc){doc.array=[]});
var changes=JSON.parse('[{"requestType":"change","actor":"91edb82e-28af-4dec-8e1d-c913283459eb","seq":2,"deps":{},"ops":[{"action":"ins","obj":"92dcf3fc-1344-4216-889b-cac6591b4cf9","key":"_head","elem":1},{"action":"set","obj":"92dcf3fc-1344-4216-889b-cac6591b4cf9","key":"91edb82e-28af-4dec-8e1d-c913283459eb:1","value":0},{"action":"ins","obj":"92dcf3fc-1344-4216-889b-cac6591b4cf9","key":"91edb82e-28af-4dec-8e1d-c913283459eb:1","elem":2},{"action":"set","obj":"92dcf3fc-1344-4216-889b-cac6591b4cf9","key":"91edb82e-28af-4dec-8e1d-c913283459eb:2","value":1},{"action":"ins","obj":"92dcf3fc-1344-4216-889b-cac6591b4cf9","key":"91edb82e-28af-4dec-8e1d-c913283459eb:2","elem":3},{"action":"set","obj":"92dcf3fc-1344-4216-889b-cac6591b4cf9","key":"91edb82e-28af-4dec-8e1d-c913283459eb:3","value":2}]}]');

tmpDoc=Automerge.applyChanges(tmpDoc,changes);

i expect that the new tmpDoc.array should be [2,1,0].
but it's an empty array '[]' in fact.
why?

**Comment by mccoysc** [comment]
@pvh

**Comment by ept** [comment]
@mccoysc In Automerge, every object you create has a unique objectId. This example doesn't work because all the list operations in your JSON data are for a particular objectId (`91edb82e-28af-4dec-8e1d-c913283459eb`), but when you create the new list object (`doc.array=[]` in the first line of your code sample), that object is given a new random UUID. You can see that by printing out `tmpDoc.array._objectId`. So the changes don't get applied because they're for a different object.

What are you trying to do? This sort of situation shouldn't arise in normal use of Automerge.

**Comment by mccoysc** [comment]
@ept

**Comment by mccoysc** [comment]
I run it in chrome browser version 70
