### ISSUE TITLE
Cannot use a Date value

### ISSUE THREAD

**Issue by m-abs** [automerge/automerge#138]
Hi,

So far `automerge` looks very promising, but I just ran into this minor problem. 
When I set a `Date` object on my `doc` an empty object is added instead of the `Date`.

```Javascript
 let doc1 = Automerge.change(Automerge.init(), "Initial value", doc => {
    doc.started = true;
    const updated = new Date();
    const updatedJSON = JSON.stringify(updated);
    doc.updated = updatedJSON;
    doc.date = updated;
  });

  console.log(doc1);
  // { started: true, updated: '"2018-12-06T10:18:09.572Z"', date: {} }
```

As you can see, the stringified `date` is stored as expected, but the `Date` object isn't.

Versions:
- automerge@0.9.2
- nodejs@10.12.0

**Comment by ept** [comment]
Ah, that's interesting. Thanks for the report, @m-abs. This is happening because `typeof (new Date()) == 'object'` and `Object.keys(new Date()) == []`, so Automerge is treating the value as the empty object `{}`. Looks like we will need to special-case values where `value instanceof Date`.

What would you expect to happen in this case? Should Automerge turn the Date object into an ISO8601 string, like JSON.stringify, or should it treat Date as a separate datatype that is turned back into a Date object when the document is loaded?

**Comment by m-abs** [comment]
Hi @ept 

When I ran into this I expected it to be an instance of Date :)

As far as I know a `Date`-object can't be frozen, but you might be able to wrap it in a `Proxy`-object and get the same effect.

**Comment by ept** [comment]
On #139 I've implemented the simpler option, which is to store and return the value as a string. What do others think — is this a good API behaviour? @pvh?

If we want to turn it back into a Date object we would need to add some metadata to the operation format that tells us how to interpret a value. That is of course possible. One thing to consider in this context is that we'll want to support Automerge in languages other than JavaScript in the future, so any datatypes we add should be widely supported; however, I imagine all mainstream languages will have a built-in datetime/timestamp datatype, so this shouldn't be a problem.

**Comment by 32bitkid** [comment]
@ept Personally, I like the solution in #139, given that Automerge is self-described as JSON-like and there is no JSON date type. The thing that I don't like about it is that it's asymmetric, so if I have to manually handle taking a value _out_, then I almost want to do it manually on both directions rather than relying on an auto conversion one way, but not the other.

Though, to me, it does raise some other interesting questions about other common types in ES2015 like `Map` and `Set`, which also can't be frozen, nor are they handled gracefully in `JSON.serialize()`... Maybe whats really needed some clearer documentation about what datatypes _can_ be persisted in Automerge, even if that is just a hard assertion of the JSON-compatible types: 

```typescript
type JSON = boolean | number | string | null | Array<JSON> | { [key: string]: JSON };
```

**Comment by pvh** [comment]
I think strictly observing JSON data type semantics is a reasonable design decision and one I'd support. A richer interface would have its advantages but choosing to move that direction could radically complicate the interface and should be approached deliberately.

For dates and other types in past projects I've used convention-based key names to recognize them and cast them back to the right type. In my case, I'd always end date keys in `_at`.

I'd be especially careful not to embrace Map/Set in the near term. Again, while I think extending the semantics of Automerge is an interesting idea it's something we should pursue deliberately. Sets, for example, have well-studied CRDT semantics, but I don't know whether we know for sure that Automerge's consistency guarantees would hold for new data types.

**Comment by ept** [comment]
After some more discussions I changed #139 to support Date objects as a primitive datatype in Automerge documents. I think we don't need to stick strictly with JSON's set of datatypes; in fact, with `Automerge.Table` (#29) and `Automerge.Text` (#41) we are already moving beyond the set of datatypes offered by JSON. Datetime/timestamp values are important in many applications and the datatype is supported in most programming languages, so I think it makes sense to support it explicitly.
