### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by unao** [automerge/automerge#142]
I think this project is super cool - thank you all for the hard work.

I wanted to suggest to consider migrating the code base to TypeScript, as it brings a lot of benefits and very little downsides. I did already initial work (~50-60% of all the work that is needed): https://github.com/unao/automerge/tree/ts and wanted to ask if it made sense to continue this path.

If there is some interest from the maintainers, I would happily discuss more details - btw. I totally understand if you prefer to stick to raw JS. In such a case I could probably help with: https://github.com/automerge/automerge/issues/105.

**Comment by pvh** [comment]
Hi @telamon -- I'm interested to hear how you were using hypermerge. 

@unao, I think Automerge is likely to stay in JS but to acquire TS types. Really good and ergonomic types for Automerge are somewhat tricky because of the dynamic nature of the underlying documents (another node could send you unexpected data and violate your local types, for example), but if you look in Hypermerge at the fork branch I believe there's an automerge.d.ts file in there.

**Comment by telamon** [comment]
@pvh I can't answer your question because i don't know what hypermerge does, it's source-code does not make sense to read without IDE assistance and/or the deluded notion of types in JS.

But it if you're on the other-hand are interested on what I'm doing in general, I suggest you drop me a pm to avoid further derailing this issue.
I'm still curious about how hypermerge is designed, just not curious enough to endure TS :)

**Comment by schrepfler** [comment]
“deluded notion of types in JS” sounds a bit biased. IMO types are a good thing, especially in library design.

**Comment by telamon** [comment]
@schrepfler of course it is biased, I hope you agree that having the opportunity to form your own opinion and bias is healthy and good for diversity?

I'm merely informing that converting a common library to sub-syntax-X is limiting it's overall compatibility and usefulness. And most importantly it hampers freedom of choice.

I couldn't care less what you choose to use in your own user-end project; you are entirely free to follow your own whims and I an fully defending your right to do so.

As for me, I have worked with many typed languages and dynamic languages for the last couple decades thus being coloured by my own experiences. So please excuse my liberal honesty in saying:
"Trying to solve complexity by adding another layer of complexity is just plain dumb"

Even if i have a different standing point - my intention is **not** to convert you, I'm merely asking you in a polite way to not pull your pants down in public spaces, and I sincerely promise to extend the same courtesy to you. :slightly_smiling_face:

**Comment by pvh** [comment]
Thanks to everyone for their input here. We may port Automerge to Typescript in the future or may not, but we certainly use it with Typescript. I'm going to close this issue before it wanders further into language wars.

**Comment by ept** [comment]
Here is one possible TypeScript type definition for Automerge:
https://github.com/inkandswitch/capstone/blob/master/src/types/automerge.d.ts
If you have a chance to give it a try, your comments on #105 would be welcome. As @pvh commented, good static types are tricky to define for Automerge since the contents of a document are inherently dynamically-typed. But the rest of the API should be amenable to static type definitions.

I am interested in having good interoperability between Automerge and TypeScript code bases, but my preference is to achieve that by adding type definitions to the JavaScript implementation, not by converting the implementation to TypeScript.
