### ISSUE TITLE
applyChanges error

### ISSUE THREAD

**Issue by mccoysc** [automerge/automerge#144]
`var savedDoc=["~#iL",[["~#iM",["ops",["^0",[["^1",["action","makeList","obj","a8575455-bda2-47ed-bac4-b5cc65fbf2fb"]],["^1",["action","link","obj","00000000-0000-0000-0000-000000000000","key","array","value","a8575455-bda2-47ed-bac4-b5cc65fbf2fb"]]]],"actor","360000B2","seq",1,"deps",["^1",[]]]]]]`

`var savedChanges=[{"ops":[{"action":"makeList","obj":"a8575455-bda2-47ed-bac4-b5cc65fbf2fb"},{"action":"link","obj":"00000000-0000-0000-0000-000000000000","key":"array","value":"a8575455-bda2-47ed-bac4-b5cc65fbf2fb"}],"actor":"360000B2","seq":1,"deps":{}},{"ops":[{"action":"makeList","obj":"4d0889d3-388d-461b-bd85-5a77ccfe2cba"},{"action":"link","obj":"00000000-0000-0000-0000-000000000000","key":"array","value":"4d0889d3-388d-461b-bd85-5a77ccfe2cba"}],"actor":"36100243","seq":1,"deps":{}},{"ops":[{"action":"ins","obj":"a8575455-bda2-47ed-bac4-b5cc65fbf2fb","key":"_head","elem":1},{"action":"set","obj":"a8575455-bda2-47ed-bac4-b5cc65fbf2fb","key":"360000B2:1","value":0}],"actor":"360000B2","seq":2,"deps":{}},{"ops":[{"action":"ins","obj":"a8575455-bda2-47ed-bac4-b5cc65fbf2fb","key":"360000B2:1","elem":2},{"action":"set","obj":"a8575455-bda2-47ed-bac4-b5cc65fbf2fb","key":"360000B2:2","value":1}],"actor":"360000B2","seq":3,"deps":{}},{"ops":[{"action":"ins","obj":"a8575455-bda2-47ed-bac4-b5cc65fbf2fb","key":"360000B2:2","elem":3},{"action":"set","obj":"a8575455-bda2-47ed-bac4-b5cc65fbf2fb","key":"360000B2:3","value":2}],"actor":"360000B2","seq":4,"deps":{}}]`

var doc=Automerge.load(JSON.stringify(savedDoc),'360000B2');
doc=Automerge.applyChanges(doc,savedChanges);

expect doc.array should be [0,1,2].
but [].

anyone know the problem?

**Comment by mccoysc** [comment]
@ept @pvh

**Comment by ept** [comment]
Hi @mccoysc. Sorry for the delay, I've been on holiday.

This is happening because you have created two different list objects (with UUIDs `a8575455-bda2-47ed-bac4-b5cc65fbf2fb` and `4d0889d3-388d-461b-bd85-5a77ccfe2cba` respectively), and assigned them to the same key `doc.array`. The object that appears by default under the key `doc.array` is `4d0889d3-388d-461b-bd85-5a77ccfe2cba` (try looking at `doc.array._objectId`), but the values 0, 1, 2 are getting added to the list `a8575455-bda2-47ed-bac4-b5cc65fbf2fb`.

The other list object appears under `doc._conflicts`, and there you can see the values 0, 1, 2. `doc._conflicts.array['360000B2']._objectId` returns the objectId of the other list.

So the problem is whatever code that is creating two different lists. If you can make it such that the list is only created in one place, and then everyone uses that list, it should work better.
