### ISSUE TITLE
When to use many documents vs one massive document

### ISSUE THREAD

**Issue by spiffytech** [automerge/automerge#168]
I'm looking for guidelines on how to structure my app that's going using Automerge. I'm recording financial transactions, and need to save the results to a dumb storage backend (one that can't merge the result of `Automerge.getChanges`, so I presume I'm using `Automerge.save`).

Looking at the Trello clone example, it looks like I should be storing all of my transactions inside a single document. Is that right? Following that model with some rudimentary tests, storing 30,000 transactions in Automerge (a back-of-the-napkin prediction of a heavy user's dataset) generates a 32MB text file. Even compressed to 4MB with zlib, that's a lot to shuttle around, and that's without any change history.

Is it recommended to store a whole dataset in a single document like this? The alternative is storing each tiny transaction in a separate document, but then I'm stuck managing most of the sync steps manually, right?

**Comment by ept** [comment]
Hi @spiffytech, sorry for the delayed reply. There's no hard and fast rule as to what things to put in the same document, and when to split it into multiple documents. The document is the granularity at which changes happen: that is, the version history, the ordering of changes, the atomicity (modifying multiple objects in a single change) are all at a per-document level. We also load an entire document from disk into memory, so that determines the practical limit for the size of a document.

In your case, if 30,000 transactions is a reasonable upper bound for the dataset size you expect, I would think it should be okay to store it in a single document. If `Automerge.save()` is too slow for this, you could store the data across several blocks (so that when you want to save a new version, you only write one block that contains the new changes, rather than rewriting the entire change history to a new file). [Hypermerge](https://github.com/automerge/hypermerge), for example, does not use `Automerge.save()`, but appends changes to a log that grows gradually. However, loading a document from disk does still require reading the entire log.

There is ongoing work that will make the storage format more efficient, which will help here. Perhaps we should also look into developing better storage backends that don't need to write or read the entire change history. Ideas for this are welcome.

**Comment by shawnd** [comment]
Hi @ept, could we consider adding some sort of mechanism to merge a chunk of changes?

For example after 10,000 transactions I may not care about the granularity of the first 1,000 transactions. So to save space I may want to merge transactions 0-1,000 into one transaction. Or maybe using a datetime range, so at the end of every day I compress all transactions into one transaction.

If its already possible to do this with the Automerge API, I'd appreciate if you could share how. Thanks

**Comment by ept** [comment]
Hi @shawnd, reducing the granularity of historical data like this is a good idea. It's not currently possible with Automerge, but I think it would be worth adding this in the future.

**Comment by ept** [comment]
Closing this issue; we can revisit snapshots and reduced-granularity history in a separate issue.
