### ISSUE TITLE
op_set internals questions: `byObject` and `deps`

### ISSUE THREAD

**Issue by edahlseng** [automerge/automerge#190]
As I'm working on updating the documentation in INTERNALS.md, two questions that I've run into:
* What exactly is the byObject portion of the local state used for? Is it a representation of the current state of each object? If so, then what's the difference between this and the state stored in the frontend?
* I don't quite understand what deps is used for. It's used very infrequently... my best guess was that this would represent the direct dependencies of any local change applied to the CRDT, but I can't see where deps is being used in order to support that guess.

**Comment by ept** [comment]
Brief notes, please expand on them:

* The `byObject` contains several pieces of state that are attached to a particular object, and thus need to be indexed by objectId. Those things are:
  * `_init`: the operation that created this object
  * `_keys`: in map objects, for each key that appears in the map, the list of operations that define the current value(s) for that key. in list objects, the keys are element IDs
  * `_inbound`: operations that link to the current objectId (used to determine the parent of a given object)
  * `_insertion` (for list objects only): for a given element ID, the operation that inserted that element
  * `_following` (for list objects only): for a given element ID, a list of operations whose reference ID is that ID
  * `_maxElem` (for list objects only): maximum counter of an element ID seen so far
  * `_elemIds` (for list objects only): the skip list managing the contents of this list
* The `deps` field in the opset keeps track of the most recent changes we have seen. Unlike the `clock` field, `deps` contains only non-redundant dependencies: that is, if A depends on B, then B will not be included in `deps`, since A already indirectly specifies the dependency on B. The `deps` field is used to populate the corresponding field when generating a new change (backend/index.js, line 140).

**Comment by edahlseng** [comment]
Thanks @ept!
