### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by edahlseng** [automerge/automerge#191]
I noticed that Dependabot is currently putting up PRs for security fixes. Is that something that we want for all dependencies? If so, I can put up a PR for a configuration to set that up, specifying the update cadence, etc.

**Comment by ept** [comment]
I don't know if it makes sense to automate this. I updated the dependencies yesterday (d05b2fee907668ff10512fa2715e25e58e23ce2a) and had to do a bunch of manual stuff in order to figure out how to continue supporting a reasonable range of Node versions, and other stuff (see commit message). While we could certainly automate something that runs `yarn upgrade` from time to time, that's not the difficult part: the difficult part is figuring out how to fix things after some dependency has made a breaking change.

**Comment by edahlseng** [comment]
Totally, Dependabot wouldn't save any of the effort of actually fixing regressions. My team has found Dependabot helpful only because it takes care of tracking when dependencies are updated. It puts up PRs for each dependency individually as they're updated, and then the PR is automatically merged in if all tests pass. When something doesn't pass, the PR is available for us to fix, and we're automatically assigned.

If we don't think that makes sense, I get it! It's an option that's available, but I agree it doesn't solve the hard part of actually fixing breakage.

**Comment by ept** [comment]
Closing this for now, but happy to revisit it again in the future.
