### ISSUE TITLE
Migrations and varying client versions?

### ISSUE THREAD

**Issue by elashpear** [automerge/automerge#204]
This isn't necessarily an issue with automerge per se but I am considering using it at work and am not sure where else to turn to for information on this problem.

I am building a mobile app that talks to a central server. Let's say I have two clients out in the wild running v1.0. I have an automerge document like so:
```javascript
{
  schema: "1.0",
  todo: [
    { title: "foo", done: false }
  ]
}
```

Now I would like to release v1.1 of the app, but I need to change the layout of the data to match this:
```javascript
{
  schema: "1.1",
  todo: [
    { topTitle: "foo", subtitle: "bar", done: false }
  ]
}
```

Let's say one user updates to v1.1. It's a mobile app so I don't really have that much control over it other than completely blocking access to the server until they upgrade, which is not a very good user experience.

But now I've got a client at v1.0 mutating the old format of the data, and another one at v1.1 mutating the new one. Is there an elegant way to handle this using CRDTs? It seems that eventually it would lead to some surprising behavior.

It seems like v1.1 will essentially need to have a migration function that converts from 1.0 format in order to convert its own data when the user upgrades. So I could theoretically just run that to transform any state I'm getting from the other client if I detect that it's required. It just seems like that could potentially get messy. And it wouldn't work in the opposite direction.

I could just ignore any incoming state that doesn't match my version, and let the clients desync until the straggler upgrades, migrates, and sends the migrated state up.

But I am curious if anyone here has ran into this problem before and has any thoughts or wisdom to offer. Is there any prior art I should be aware of? Feel free to close this issue or direct me to another discussion forum if you feel this is not the appropriate place for this. Thank you!

**Comment by edahlseng** [comment]
Hi @elashpear! Exciting question...

You're right that this question isn't related to Automerge, per se – it's a problem that comes from the application layer built above Automerge. That means that the solution to this problem is also application dependent. The way that you end up solving this for your particular mobile app might be a different approach than the way someone else with a completely different use case solves it. Nevertheless, I can share my two cents on how I've built extensible schemas on top of Automerge. (I should caveat that I'm by no means the expert, and am even relatively new to Automerge myself. Hopefully I can share a helpful tidbit or two, though.)

There are two different types of evolution that a schema can undergo: growth and change.

### Growth

Growth refers to both schema additions and dropping support for previously existing features. I refer to these as _growth_ because they can happen organically, without a coordinated effort. Whenever possible, I try to structure my applications in a way that my Automerge schemas _grow_ so that I can avoid _changing_ them.

Taking the example that you listed above, we can imagine that your app starts with the following:

```js
{
  todo: [
    { title: "foo", done: false }
  ]
}
```

When you want to release the next version of the app, the schema might follow a format more like this:

```js
{
  todo: [
    { title: "foo", subtitle: "bar", done: false }
  ]
}
```

The key is that in this case **we didn't change the key `title` to `topTitle`**. We only _added_ the `subtitle` field. Since this is just a new key in the document, Automerge will happily handle it, on both new versions of the app and old versions of the app. Any user who has the new version of your app would be able to see and edit the subtitle. Users on old versions of your app would not see the `subtitle`, but Automerge will still be storing the data under the hood. As soon as these users upgraded to the latest version of your app, they would suddenly see the subtitle appear since the data exists in the document.

Another example is dropping support for data. Continuing with the example of your app, let's say that version 1.0 includes a due date: 

```js
{
  todo: [
    { title: "foo", done: false, dueDate: new Date("2019-08-10T10:00") }
  ]
}
```

For whatever reason, maybe you drop support for the due date in version 1.1:

```js
{
  todo: [
    { title: "bar", done: false }
  ]
}
```

This is still growth because both versions of your app can work with the same data. Automerge in version 1.1 of your app will continue to handle `dueDate`s behind the scenes, they just won't be displayed in the app. Users who still use version 1.0 will then be able to continue using the due date feature until they upgrade, at which point it will no longer be visible. (Technically the data would still exist in the Automerge document, so you could even add the due dates back in in version 1.2, but that becomes a product question rather than a technical one.)

I've found that the vast majority of ways that I've ever wanted to evolve a schema can be satisfied through this growth approach. Usually it just comes down to picking good names for keys. This kind of evolution is vastly preferable to _change_ as described below, because it involves little to no coordination, and it often provides a better experience for users as well.

### Change

Sometimes (I always try to avoid it, but sometimes it's unavoidable), schemas evolve in a way that _changes_ the meaning of an item. Let's say that version 1.0 of your app allowed links in todo items:

```js
{
  todo: [
    { title: "foo", done: false, link: "www.google.com" }
  ]
}
```

Perhaps you encountered issues with these links, because sometimes they included the protocol, but sometimes they didn't. In version 1.1 of your app, you decided to change the meaning of `link` to one that _requires_ a protocol:

```js
{
  todo: [
    { title: "foo", done: false, link: "https://www.google.com", version: 2 }
  ]
}
```

(This isn't the best example, as you could handle this change in ways that don't affect your Automerge schema, but it's the best example I could come up with on the spot, so let's go with it.)

The key with these kind of changes is that you don't want older versions of the application to write to a portion of the document that has been edited by a newer version of your application. If that were possible, then an older version of the app could write a `link` that doesn't have the protocol included, which might not work in the newer version of your app. In order for this to work, old versions of your app should disallow edits to portions of the document that have a version greater than what it supports. There are a few other details that I tend to follow:
* **Build in this support from version 1.** Supporting these kind of changes should be a last resort to begin with, but they are next to impossible if the first version of the application isn't built to handle them.
* **Each individual object in a document has a version.** You'll notice in the example above that I put the `version` key in the todo item itself, rather than the top level of the document. I usually do this to minimize breakage for users. For example, if a user has upgraded to app version 1.1 on one device, but they've only edited one todo, there's no need for me to prevent them from interacting with the other 237 todo items on another device until they've had a chance to upgrade their app. (This can pose a UI challenge, however, to be able to indicate when certain actions are allowed and others aren't. If you can make it work, though, it's an awesome experience for users.)
* **Future versions of your app should support all previous versions.** Unless you can guarantee that everyone has upgraded past a given version (and they can't downgrade), it's best to support every previous version of the schema (even if that just means converting an item to the latest schema and updating the version number).
* **Use integers or dates for the version numbers.** Since we've categorized _change_ as only referring to schema updates that change meaning, there's no reason to use a version number like 1.1.2. Simply use an integer, because it can be easily compared with e.g. `<=`. (I actually often use dates instead of integers, because dates can still be easily compared with `<=`, and they give the added benefit that it reminds me of _when_ I changed the schema.)

I hope this helps! Let me know if anything wasn't clear... Good luck with your project! 🙂

**Comment by elashpear** [comment]
Thanks for the detailed reply! Certainly good food for thought. In my particular situation I am making a React Native app that uses Redux internally to manage the majority of the app state, and I am trying to figure out a way to seamlessly sync this state between devices. CRDTs seemed like a natural fit for this problem as the user isn't really editing the state directly in almost all cases, it's a product of whatever actions they've taken in the app.

I don't see why you can't have each reducer itself be a CRDT. (If you're not familiar with the Redux lingo, a "reducer" is basically a pure function of `(state, action object) => new state`.) And internally each one could be using something like automerge or another type of CRDT graph to ensure commutativity, associativity, and idempotency. In fact, this is what's implemented by the [redux-scuttlebutt](https://medium.com/@grrowl/redux-scuttlebutt-eventually-consistent-shared-state-among-peers-191d48102079) library, although it doesn't seem to enforce that the state is a CRDT.

But this does mean that I'll most likely need to figure out how to resolve all possible conflicts in the least-surprising, automatic manner. I can't really prevent the user from doing things like navigating through the app. 🤔 Although I may be able to display a warning that their state will not sync until they upgrade or something like that...

I may be able to get us to follow something like the guidelines you described above, but I am trying to architect a system that will be used by multiple teams so I want to do my best to figure out a solution here that is easy to reason about and maintain in a complex production app. (I know it says automerge isn't intended for production use yet, but we've shipped with worse npm packages I'm sure. 😉 ) I looked recently for an example of a large app state blob from one of our apps and found it had over 11k unique keys and was 30k in size as a minified string. That is to say, it's big and complex, so I am trying to find a solution that will be easy to reason about at that scale. I've had good luck finding introductory material about CRDTs and nice libraries like this, but little to no info about the kinds of messy situations you can get into in a production app like the one I am describing here.

**Comment by edahlseng** [comment]
I've also found that Redux works quite well with Automerge. Using them both together feels almost like it was meant to be. I haven't ever tried breaking down separate reducers as different CRDTs, though, that's some food for thought.

It sounds like you'll definitely be pushing the scale for the level of complexity for apps built with Automerge. I haven't worked with anything that large yet; I wonder if anyone else in the community has... I'd love to hear more about the nuances of what you learn as you explore this space!

**Comment by stoically** [comment]
Similar questions arise when doing distributed eventsourcing, so [Versioning in an Event Sourced System](https://leanpub.com/esversioning/read) might have some food for thought as well.

**Comment by ept** [comment]
Thanks for the good discussion here. Regarding Redux, I've seen a few projects use it (or very similar patterns) with Automerge, and it seems to work fine. You probably need to send not only your local user input to the reducer, but also any changes that come in over the network (use `Automerge.applyChanges()` to process incoming changes from the network in the reducer).

The problem of handling different versions of an app side-by-side is an example of the schema evolution problem. Automerge kinda punts on the problem because it only deals with "dynamically typed" JSON without an explicit schema; as @edahlseng suggests, the easiest way is to add new optional properties to objects, and clients that don't understand a property ignore it (but preserve it). We have discussed adding explicit schema support to Automerge, and in doing so we would probably take inspiration from the way schema evolution is handled in Thrift, Protocol Buffers, or Avro. (I have a [blog post](https://martin.kleppmann.com/2012/12/05/schema-evolution-in-avro-protocol-buffers-thrift.html) describing how these formats handle schema evolution, and Chapter 4 of [my book](https://dataintensive.net) (shameless plug) covers it in more detail.)

Since @stoically mentioned event sourcing: that might be an alternative way to go. In an event sourced model, the data is represented as an append-only log of immutable events, and the current application state is derived from those events, in a way that strongly resembles a Redux reducer. This is quite a different approach than CRDTs, since CRDTs are all about handling concurrent mutations to some state, while event sourcing is all about making state immutable. But it might be possible to bridge those worlds somehow.
