### ISSUE TITLE
String interface for Automerge.Text

### ISSUE THREAD

**Issue by agentofuser** [automerge/automerge#207]
Hi, thank you very much for Automerge, it's been a pleasure using it! I'm trying to think of the best way to do something like this:

   1. convert Automerge.Text list to a string (say, `prevString`)
   1. use regular string transformations (e.g. string.replace()) to get a `nextString`
   1. diff `prevString` and `nextString`
   1. perform minimum number of operations on original Text to match `newString`

Is this "minimum-diff-ops" something Automerge does itself if I just replace the old Text object with `new Automerge.text(newString)` or do I need to do it on my side? Thank you.

**Comment by ept** [comment]
Hi @agentofuser, replacing the old Text object with a new one will not work correctly: if two users make changes concurrently, the result will be a conflict between the two new Text objects, and they will not be merged automatically. In order to get the Automerge merging behaviour, the changes need to be expressed using `Text.insertAt(...)` and `Text.deleteAt(...)`.

It might make sense in the future to add a diffing feature to Automerge that can do what you suggest. For now, you could find a diffing library on npm and use it to generate the insert/delete operations. I think there are a few available, but I don't know which is good.
