### ISSUE TITLE
Performance issue with big change in Automerge.Text

### ISSUE THREAD

**Issue by CGNonofr** [automerge/automerge#212]
I'm trying to use Automerge.Text to make a collaborative code editor

It works fine except when trying to replace the whole code (select all => paste new code)
Even with not-so-big codes, the browser freeze for many seconds, and the generated changes are huge

I understand that a delete change is made for every previous character and a add + set change is  made for every new character

What can be done about it?

**Comment by ept** [comment]
Hi @CGNonofr, thanks for highlighting this. It's a known issue, which has been discussed in #89 and #134 for example. We have profiled the code, and all the quick and easy fixes have already been done. Making significant further progress on the performance will unfortunately require ripping out several of Automerge's core internal data structures and replacing them with more efficient ones, which is a substantial amount of work.

I am actively working on a big refactoring to prepare for this change of data structures. I expect things will get a lot better over the coming months. For now, I will close this issue since we already have #89 and others discussing it.

**Comment by CGNonofr** [comment]
Thank you for your detailed answer, I will keep an eye on your work and will try to help if possible
