### ISSUE TITLE
Undoing both insertion and delete still keeps inserted text

### ISSUE THREAD

**Issue by trbrc** [automerge/automerge#216]
## Steps to reproduce

1. Insert some characters into a Text in document 1
2. Sync the changes to document 2
3. Delete the characters in document 2
4. Undo the insert in document 1
5. Undo the delete in document 2
6. Merge the changes

## Expected result
Since the edit that inserted the characters was undone, you would expect the inserted characters to be missing from the end result.

## Actual result
The characters are still present in the end result.

Example code:

```js
// 0. Setup
var base = Automerge.init();

base = Automerge.change(base, 'Base text', doc => {
  doc.text = new Automerge.Text();
  doc.text.insertAt(0, 'B', 'A', 'S', 'E');
});

var doc1 = Automerge.init();
doc1 = Automerge.merge(doc1, base);

var doc2 = Automerge.init();
doc2 = Automerge.merge(doc2, base);

// 1. Insert some characters into a Text in document 1
doc1 = Automerge.change(doc1, 'Insert', doc => {
  doc.text.insertAt(2, 'i', 'n', 's', 'e', 'r', 't');
});

// 2. Sync the changes to document 2
doc2 = Automerge.merge(doc2, doc1);

// 3. Delete the characters in document 2
doc2 = Automerge.change(doc2, 'Delete', doc => {
  doc.text.deleteAt(2, 6);
});

// 4. Undo the insert in document 1
doc1 = Automerge.undo(doc1, 'Undo insert');

// 5. Undo the delete in document 2
doc2 = Automerge.undo(doc2, 'Undo delete');

// 6. Merge the changes
var final = Automerge.merge(doc1, doc2);

// Expected: "BASE". Actual: "BAinsertSE"
console.log(final.text.toString());
```

**Comment by trbrc** [comment]
I suppose this is a consequence of [this](https://github.com/automerge/automerge/blob/8a40e46bf1b8593a4c08ce2b8ab928b7c1c3c018/README.md#undo-and-redo):

> Undo works by applying the inverse operation of the local user's most recent change [...] Both undo and redo create new changes

So effectively, when you undo a delete, the original insertion edit is no longer connected to the text, because your undo actually inserts it again. As a consequence, whoever originally inserted the text has now lost control over it.

Does this mean that if a user selects all and accidentally hits delete, then immediately hits undo, they have already destroyed the undo history of all other users?

**Comment by ept** [comment]
Hi @trbrc, sorry for the delay getting back to you. It's not actually obvious to me what the desired behaviour should be in this case, since the two undos are in conflict with each other. The current Automerge behaviour seems like a valid one to me, or do you think it really violates user expectations?

The following is happening here:

* The initial insertion of text creates a text position for each character, and assigns the respective character to each text position.
* The deletion of the text removes those characters from the text positions.
* The undo of the insertion also removes those characters from the text positions.
* The undo of the deletion re-assigns those characters back to the text positions where they were.

So here we have a concurrent removal and assignment of characters to text positions. The Automerge policy in this case is to retain the assignment (since the removal affects only causally prior values). You can see the same behaviour in this simpler example:

```js
let s1 = Automerge.from({x: 1}), s2 = Automerge.merge(Automerge.init(), s1)
// Concurrent deletion and assignment to the same property x:
s1 = Automerge.change(s1, doc => delete doc.x)
s2 = Automerge.change(s2, doc => doc.x = 2)
Automerge.merge(s1, s2)
// returns { x: 2 }
```

> Does this mean that if a user selects all and accidentally hits delete, then immediately hits undo, they have already destroyed the undo history of all other users?

Not sure what you mean with destroying undo history. Each user's undo history is independent, and is unaffected by edits made by other users.

**Comment by trbrc** [comment]
Don't worry! Thank you for your great work here.

> It's not actually obvious to me what the desired behaviour should be in this case, since the two undos are in conflict with each other. The current Automerge behaviour seems like a valid one to me, or do you think it really violates user expectations?

Yes, I'd say this goes against most people's intuition about how undo should work. I realize now that I sort of left unexplained precisely why this is unexpected, and I also misunderstood some of how Automerge behaves, so I'll try to walk it through in more detail.

The expected outcome of pressing undo under normal circumstances is something like: "Restore the document to what it was like before my latest edit". Of course this doesn't work in a collaborative environment, where it would undo other users' changes too. So a more appropriated outcome for undo in collaboration is: "Create a version of the document that is as if my latest edit never happened".

If that's the behavior we want, we should also expect that if we have some sequence of edits that include undo, and compare it to the same edits but where our "undone" edits never happen in the first place, the end result in both cases should be the same.

That's what's being violated in my example. If we remove all the edits that are undone, then all that's left is this:

```diff
  // 0. Setup
  var base = Automerge.init();

  base = Automerge.change(base, 'Base text', doc => {
    doc.text = new Automerge.Text();
    doc.text.insertAt(0, 'B', 'A', 'S', 'E');
  });

  var doc1 = Automerge.init();
  doc1 = Automerge.merge(doc1, base);

  var doc2 = Automerge.init();
  doc2 = Automerge.merge(doc2, base);

- // 1. Insert some characters into a Text in document 1
- doc1 = Automerge.change(doc1, 'Insert', doc => {
-   doc.text.insertAt(2, 'i', 'n', 's', 'e', 'r', 't');
- });

  // 2. Sync the changes to document 2
  doc2 = Automerge.merge(doc2, doc1);

- // 3. Delete the characters in document 2
- doc2 = Automerge.change(doc2, 'Delete', doc => {
-   doc.text.deleteAt(2, 6);
- });

- // 4. Undo the insert in document 1
- doc1 = Automerge.undo(doc1, 'Undo insert');

- // 5. Undo the delete in document 2
- doc2 = Automerge.undo(doc2, 'Undo delete');

  // 6. Merge the changes
  var final = Automerge.merge(doc1, doc2);

- // Expected: "BASE". Actual: "BAinsertSE"
+ // Expected: "BASE". Actual: "BASE"
  console.log(final.text.toString());
```

The end result here is different, and expected. To me this should also have been the end result in the original example. It's unexpected that undoing the delete can insert characters that we pretend were never inserted in the first place.

> So here we have a concurrent removal and assignment of characters to text positions. The Automerge policy in this case is to retain the assignment (since the removal affects only causally prior values). You can see the same behaviour in this simpler example:

I don't agree that there is (or should be) a "concurrent removal and assignment", because this particular removal means the assignment shouldn't happen at all. This entanglement can probably only happen when multiple concurrent undo is involved, otherwise you just get a regular conflict as shown in your example, and that needs to be resolved one way or another.

> > Does this mean that if a user selects all and accidentally hits delete, then immediately hits undo, they have already destroyed the undo history of all other users?
> 
> Not sure what you mean with destroying undo history. Each user's undo history is independent, and is unaffected by edits made by other users.

Sorry, I was confused here about what was going wrong in my example, and drew this incorrect conclusion without checking if I could reproduce it. For what it's worth, I was under the impression that step 5 (undoing the delete) inserted completely new but identical text, causing step 4 (undoing insert) to no longer know how it should modify the document. From that I drew the conclusion that if someone deletes everything and then presses undo, every other users' history would be useless, because it applies to data that is no longer in the document. I see now that it's only if an undo happens before merging that its effect is lost.

**Comment by ept** [comment]
I've been continuing to think about this. I see what you're saying — if the original insert never happened, then any downstream operations based on it (deleting the insertion, undoing the deletion) cannot have happened either.

However, I currently don't have a mental model for what the logic would look like in a system that behaves as you propose. I suspect that the algorithm would have to track the provenance of each operation; then, if a prior operation is invalidated by an undo, dependent operations could be undone as well. The algorithm is unclear to me, though. What counts as a dependency? (In your case, the deletion depends on the prior insert, but you could make an argument that an insert can also depend on a prior insert.)

If you are serious about wanting to change the merge semantics in this way, I would suggest coding up a rough prototype of the algorithm, so that we can run some more examples through it and observe its behaviour.

**Comment by trbrc** [comment]
Here's a rough thing that at least seems to work for my original example. It treats undo and delete as two separate types of edits.

https://gist.github.com/trbrc/a48bf48e04cdd0e8e2354821151ee1eb

**Comment by ept** [comment]
For the upcoming Automerge 1.x release series we have removed the undo feature, because it was a bit of a hack. Since this issue refers to that feature, I am going to close it. I have opened a new issue #318 for bringing back the undo feature (in better form) in the future, and linked to this issue as something to think about when we get to that stage.
