### ISSUE TITLE
Not using TypeScript is shooting yourself in the foot

### ISSUE THREAD

**Issue by steida** [automerge/automerge#220]
I know, stupid annoying comment. Feel free to close it immediately and I will immediately send $500 to charity. No kidding, I am serious and I will post a screen-shot.

I just wanted to say it because I suppose Automerge is a super awesome piece of work, and with TS it would be even better.

**Comment by steida** [comment]
✨

**Comment by pvh** [comment]
There are (tested) Typescript bindings. Feel free to use them and suggest improvements if you see any, but Automerge is written in JS with very few dependencies to ensure it is broadly applicable.

As the year gets late it's not uncommon to think about charitable giving. Personally, I'd set aside a consistent percentage of my annual income and divide it between five or six charities in a single annual cheque to each. Large donations are more operationally efficient -- less overhead in donor management -- and I try to spread my donations between a mix of national and regional issues including the environment, homelessness, and women's health. I find this approach also helps throughout the year when I receive one-off requests. With a budget and a strategy I'm able to make deliberate decisions rather than responding in the moment to each request.

Your mileage may vary, of course. Best of luck in using Automerge.
