### ISSUE TITLE
Swapping in an alternative Text/List CRDT like LSEQ?

### ISSUE THREAD

**Issue by nybblr** [automerge/automerge#221]
Hi folks! I've been following the JSON CRDT awesomeness for a few years now.

From https://github.com/automerge/automerge/issues/212, it sounds like performance for text/ordered lists gets rough for substantial documents, possibly because of the underlying algorithm (tradeoff of tombstones and fast insert/remove).

So first question: what is the current strategy for Text/Ordered Lists? OT? RGA? This code for example:
https://github.com/automerge/automerge/blob/master/frontend/apply_patch.js#L317-L383

Follow up question: I've been using the LSEQ CRDT in collaborative frontend experiments for a few years (like Google Docs). It's a proper CRDT with some amazing performance properties, especially for large documents (keeping memory usage lower than W00T/Logoot or tombstone strategies, but with O(log(n)) for insertion/removal.

The implementation I've been using supports the same insertAt/removeAt operations, so I'm thinking it might be straightforward to experiment with an alternative merge strategy.

What are your thoughts? Any caveats or recommendations on how I could take this for a spin?

**Comment by ept** [comment]
Hi @nybblr! Automerge uses (a variant of) RGA for text and lists. I am not keen on LSEQ, because it may interleave text that is concurrently inserted at the same position (see [this paper of ours](https://martin.kleppmann.com/2019/03/25/papoc-interleaving-anomalies.html)).

Our implementation of RGA is also O(log(n)) for insertions and deletions; unfortunately, that asymptotic performance hides the fact that there is quite a big constant factor. I expect that a simple implementation of any CRDT will have similar problems.

On the `performance` branch in this repository I am working towards a new implementation that has much better performance and scalability than the current one. The idea is to retain the current CRDT semantics, API, and data model, but to replace the internal data structures with more efficient ones. I plan to write about it more as this implementation develops.

**Comment by nybblr** [comment]
@ept Fantastic notes, thanks Martin! RE interleaving issues, that's pretty awesome, looks like I have some reading to do. I'll check out the `performance` branch for sure!

A few follow-up questions:

1. RGA is tombstone based (right?) — does that cause longterm memory issues and call for occasional garbage collection across replicas?
2. From the slidedeck, if `t` and `e[]` for the insert op are globally unique timestamps, does that imply a central clock source for all peers? Or is causality tracking enough? Say, counters or version vectors?
3. The technique you used to prevent interleaving with RGA makes a lot of sense — before I descend into the rabbit hole too far, do you think your technique would have a parallel for an LSEQ based on LogootSplit? [LSEQSplit](https://hal.archives-ouvertes.fr/hal-01552799/document). The goal being to get the interleaving benefits, but avoid tombstones and relaying long `e[]`s over the network.

**Comment by ept** [comment]
1. Yes, RGA uses tombstones. I think this is okay for now, as in most cases, the tombstones are not really the dominant cost. Also, I think it is desirable to retain history (so you can see what was changed when), and that requires remembering deleted parts of the document anyway.
2. These are all logical timestamps, such as [Lamport timestamps](https://en.wikipedia.org/wiki/Lamport_timestamps). No clock sync is required.
3. I haven't looked at LogootSplit/LSEQSplit in detail. My fear is that they add a lot of complexity to the CRDT algorithm, for a performance improvement that is small in many cases. I think a more promising approach is to keep the CRDT algorithm simple, and to apply compression to the metadata (which is what I'm doing on the performance branch). Time will tell how well that approach works in practice.

**Comment by KB1RD** [comment]
Hello, I've been working on the [Matrix Notepad](https://github.com/KB1RD/matrix-notepad) project, which uses a Logoot-based CRDT over the [Matrix](https://matrix.org/) communication network to collaborate on basic text documents. I had plans to make the current sequence-only CRDT (which I creatively named Logootish, since it's a Logoot derivative) work with JSON-like objects as well to be used with rich-text editing down the road. The `logootish-js` repository is [here](https://github.com/KB1RD/logootish-js/). You are right that the Logootish algorithm would end up being more complex -- Mine is 736 and 331 lines in the two core files (not including the specialized binary search trees to make it possible). What may be of interest is that I have a [solution to the conflict detection problem](https://github.com/KB1RD/matrix-notepad/wiki/Logootish#multi-branch-system) that doesn't have the interleaving issues present in Logoot and I'd be curious to see what you think. It involves requiring explicit merges between multiple user's document copies when an edit happens on an atom with existing data. I'm going to do some research into the other algorithms that you mentioned to see if my merge idea would be applicable to those as well.

I mentioned wanting to work on a JSON-like collaboration CRDT. I think that I will move my efforts over to making Automerge replace `logootish-js` in Matrix Notepad as soon as this text/list CRDT issue is resolved. This library looks great and I'd be happy to do what I can to help out!
