### ISSUE TITLE
CRDT Custom Type Table.set() not detecting changes

### ISSUE THREAD

**Issue by msallat** [automerge/automerge#228]
I want to _alter_ the contents of an automerge table by using _Table.set(id: UUID, value: T)_. But I'm having an issue, that the connection callback _(sendMsg)_ is not being fired after applying changes to a document. The following part is properly working where I add a new object by using _Table.add(item: T)_. Removing via _Table.remove(id: UUID)_ is also working. What could cause this issue?

**This DOES work**:
```
    let document: Doc<TodoDoc> = Automerge.init<TodoDoc>();
    let docset = this.docSet.setDoc('docset-id-1', this.document);
    let connection: Connection<TodoDoc>;

   constructor() {
     this.connection = new Connection<TodoDoc>(this.docSet, this.sendMessage.bind(this));
     this.connection.open();
   }
   ....
    const changedDoc = Automerge.change(this.document, 'Create todo', (doc: Doc<TodoDoc>) => {
      const newTodo: Todo = {
        id: todo.id,
        title: todo.title,
        complete: todo.complete,
        createdAt: todo.createdAt,
        updatedAt: new Date().toISOString(),
      };

      doc.todos.add(newTodo);
    });

    const currentChanges: Change[] = Automerge.getChanges(this.document, changedDoc);
    this.docSet.applyChanges('docset-id-1', currentChanges);
```

**This DOES NOT work**:
```
    const changedDoc = Automerge.change(this.document, 'Update todo', (doc: Doc<TodoDoc>) => {
      const currentTodoById = this.document.todos.byId(todo.id);

      currentTodoById.title = 'Updated Title';
      currentTodoById.complete = true;
      currentTodoById.updatedAt = new Date().toISOString();

      doc.todos.set(todo.id, currentTodoById)
    });

    const currentChanges: Change[] = Automerge.getChanges(this.document, changedDoc);
    this.docSet.applyChanges('docset-id-1', currentChanges);
```

**Comment by ept** [comment]
Hi @msallat, sorry for the slow reply. I noticed two things in your example:

1. When you want to update a row in the table, you need to access it through the object provided to the change callback. That is, instead of `this.document.todos.byId(id)` you need to do `doc.todos.byId(id)`.
2. You're creating Todo items with an `id` property — you don't show where this ID comes from, but please note that the `todos.byId(...)` method does not use an ID that you generate. Rather, Automerge generates its own ID when you insert a row, and this ID is returned by the `doc.todos.add(newTodo)` method. I suggest that you use this Automerge-generated ID rather than creating your own.

Hope that solves your problem. Please let me know if you have any further troubles.

**Comment by ept** [comment]
Oh, another thing. I just realised that the call to `Automerge.Table.set()` does not do what you'd expect: it doesn't actually record any change. I have just created #243 to rename this method, since it's confusing.

You don't need to call `set()` at all. This is sufficient to update a row in a table:

```js
const changedDoc = Automerge.change(this.document, 'Update todo', (doc: Doc<TodoDoc>) => {
  const currentTodoById = doc.todos.byId(todo.id);
  currentTodoById.title = 'Updated Title';
  currentTodoById.complete = true;
  currentTodoById.updatedAt = new Date().toISOString();
});
```

**Comment by msallat** [comment]
Hi @ept,

thanks for your anwser! 
Changing `this.document.todos.byId(id)` to `doc.todos.byId(id)` did the trick.
