### ISSUE TITLE
Recommended pattern with IndexedDB

### ISSUE THREAD

**Issue by pspeter3** [automerge/automerge#229]
I was wondering what the best practice was for storing Automerge in IndexedDB. Do you store serialized documents or changes in the IndexedDB?

**Comment by pvh** [comment]
Hard to say categorically, but I expect you should store the changes.

**Comment by pspeter3** [comment]
@pvh Thanks for answering! Is there a good heuristic about when to store changes vs when to store the doc itself?

**Comment by pvh** [comment]
At least currently, the "doc" is just a serialization of all the changes. :) Here is fine for questions but the Slack is probably best.

**Comment by pspeter3** [comment]
Thanks! I'll come to the Slack 😄

**Comment by HerbCaudill** [comment]
@pspeter3 - I've been working on a wrapper library for Automerge called [Cevitxe](https://github.com/DevResults/cevitxe) that supports using IndexedDB for storage. 

We ended up storing both the history of changes and the latest snapshot for each document. 

You could just store the changes, but it's costly to rehydrate the document from its full change history every single time, especially since most of the time you're just interested in its current state. 

The code for our IndexedDB adapter is [here](http://github.com/DevResults/cevitxe/blob/master/packages/cevitxe-storage-indexeddb/src/index.ts ). The [Repo](http://github.com/DevResults/cevitxe/blob/master/packages/cevitxe/src/Repo.ts) class uses that adapter. 

Hope this helps - I'm on the Automerge Slack if you have questions.

**Comment by pspeter3** [comment]
Super helpful, thank you!
