### ISSUE TITLE
Merging Arrays

### ISSUE THREAD

**Issue by sjmiles** [automerge/automerge#244]
Related to #4?

[A Conflict-Free Replicated JSON Datatype](https://arxiv.org/abs/1608.03960) contains this diagram:
![image](https://user-images.githubusercontent.com/98045/77472393-15d38e80-6dd1-11ea-9e69-f3a451410119.png)

But a quick test in [Glitch ](https://glitch.com/edit/#!/automerge-example-1?path=script.js:1:0) produces:
```
one.flams = []; one.flams.push('a', 'b', 'c');
{
  "flams": [ "a", "b", "c"]
}
two.flams = []; two.flams.push('d', 'e', 'f');
{
  "flams": ["d", "e", "f"]
}
merge = Automerge.merge(one, two)
{
  "flams": ["d", "e", "f"]   // sometimes "flams": ["a", "b", "c"]
}
```
It seems there needs to be special handling to separate the notion of _create this thing if it doesn't exist_ from _replace this thing with a new empty instance_.

Good chance I'm just holding it wrong, any advice is appreciated.

**Comment by ept** [comment]
Hi @sjmiles, yes, this is indeed related to #4. Automerge and the JSON CRDT paper take different approaches to object nesting: in the paper, an object is defined by its path from the root, whereas in Automerge, an object has a unique identity that is assigned when the object is created. In your test, the two lists have distinct identities, and so they are not merged. Instead, the two concurrent assignments to the `flams` field produce a conflict, and you can find the conflicting objects by using `Automerge.getConflicts(doc, 'flams')`.

To get the expected merging behaviour, you need to do `flams = []` on one node, merge (so that the other node also has the array), and then you can insert items into the array on both nodes. That will then result in either `['a', 'b', 'c', 'd', 'e', 'f']` or `['d', 'e', 'f', 'a', 'b', 'c']` as you would expect.

As you see from the discussion on #4 this is a tricky problem, and it is not obvious what the right behaviour should be.

**Comment by sjmiles** [comment]
Thank you for the quick reply, really appreciate it.
