### ISSUE TITLE
Detect automerge object

### ISSUE THREAD

**Issue by tom-sherman** [automerge/automerge#250]
I'm creating a React utility state hook ([here](https://github.com/tom-sherman/use-automerge)) backed by automerge.

What I'd really like for my API is to accept plain objects as well as automerge documents for the initial state, unfortunately passing a document to `Automerge.from` doesn't seem to work as seen by this failing test: https://github.com/tom-sherman/use-automerge/blob/master/src/use-automerge.test.ts#L29-L35

There's a couple of ways I can think of to solve this:

- Accept documents in init/from
- Add a public symbol to to each document root eg. `Symbol(automerge): true` and then export that symbol as part of the public API.

**Comment by ept** [comment]
Hi @tom-sherman, what is the expected behaviour if an existing Automerge document is passed to `Automerge.from()`? Do you want it to just return that object verbatim, or construct a new Automerge document containing the same data?

In order to test whether a given object is an Automerge document or not, one approach you could use is to call `Automerge.getObjectId(doc)`, which should return a string if it is an Automerge document, and undefined if not.

**Comment by tom-sherman** [comment]
@ept

> what is the expected behaviour if an existing Automerge document is passed to `Automerge.from()`?

That is a very good point. I think I expected the samantics to be similar to `Array.from`. With `Array.from` you get a new array object but each item in the new array is referentially equal. I think this translates to `Automere.from` returning a new document with exactly the same contents, equivalent to `Automerge.merge(Automerge.init(), doc)` maybe.

> In order to test whether a given object is an Automerge document or not, one approach you could use is to call `Automerge.getObjectId(doc)`, which should return a string if it is an Automerge document, and undefined if not.

I think this would satisfy my use case, in which case a change to `Automerge.from` wouldn't be necessary for me.

**Comment by ept** [comment]
Okay, sounds good. I'll close this issue then, but please get back in touch if you run into any more issues.
