### ISSUE TITLE
How to sync an automerge document with a Firebase database?

### ISSUE THREAD

**Issue by nickjanssen** [automerge/automerge#251]
Thank you for making this amazing library.

I'm using Firebase, where it's not always possible to update a node at a single location because the writes can get too big. Firebase's realtime database has a limit of 16MB per write location.
In other words, I'm unable to write the output of `Automerge.save(finalDoc);` to a database endpoint once the document becomes over 16MB, which will probably be reached very quickly.

How can one sync an automerge document to a firebase database endpoint, taking into account the fact that there is a write size limit?

**Comment by ept** [comment]
Hi @nickjanssen, you're going to like the upcoming binary encoding format for Automerge, which is orders of magnitude smaller :)

In the meantime, you can break the Automerge data size into smaller chunks by taking the array returned by `Automerge.getAllChanges(doc)`, splitting it into sub-arrays, and JSON-encoding each chunk separately. To deserialise, concatenate the JSON-parsed arrays and feed them all to `Automerge.applyChanges()`.

**Comment by nickjanssen** [comment]
Neat, I'll this try! Thank you :)

**Comment by pvh** [comment]
I'd actually solve this differently. Instead of syncing the whole "finalDoc", I'd use getChanges() to request the accumulated changes at intervals and store those along with the vector clock at that point. Then you can batch & store groups of changes at some convenient interval to firebase and download blocks of changes to apply on local nodes. By storing the vector clock alongside you can determine what you have / need.
