### ISSUE TITLE
Fixed-length actor IDs / signature checking?

### ISSUE THREAD

**Issue by ept** [automerge/automerge#256]
A question for Automerge users, especially those building data sync layers (@HerbCaudill, @pvh). In the context of developing the [Rust implementation](https://github.com/automerge/automerge-rs), @alexjg and @orionz have asked: can make actor IDs a fixed length?

At the moment, actor IDs are variable-length. This provides some flexibility: Automerge uses 128-bit random UUIDs by default, but IIRC Hypermerge uses 256-bit actor IDs (where the actor ID is the Ed25519 public key of the underlying hypercore). Being able to put the hypercore public key directly in the Automerge actor ID saves having to maintain a separate lookup table associating hypercore keys and actor IDs.

Background: in Rust, data structures whose size is known at compile time can implement the [Copy trait](https://doc.rust-lang.org/std/marker/trait.Copy.html), which (as I understand it) gives values of that type call-by-value semantics (rather than call-by-reference). Such values can be passed on the stack, rather than using a reference to a heap-allocated object. This would simplify the implementation and perhaps have performance benefits.

What do you think of moving to fixed-size actor IDs? This would require deciding on the size to use. Plausible choices seem 16 bytes (128 bits) or 32 bytes (256 bits). Bigger sizes would be too wasteful, smaller sizes would have too high a risk of collision.

A related question: now that Automerge is checking hash chains to ensure integrity (#200), should it also verify cryptographic signatures on changes? If we make actor IDs 256-bit Ed25519 public keys (like Hypermerge), then we could quite easily add signatures too. This would guarantee that only the owner of the corresponding private key can generate changes originating from a particular actor ID. This authenticity check would make the data self-verifying to a greater extent. However, one could also argue that signature checking does not need to be part of the Automerge core, and should be handled in a separate library layer.

Any opinions, both on fixing the size of actor IDs, and on adding signature checking?

**Comment by scotttrinh** [comment]
Curious outsider's perspective:

> If we make actor IDs 256-bit Ed25519 public keys (like Hypermerge), then we could quite easily add signatures too. This would guarantee that only the owner of the corresponding private key can generate changes originating from a particular actor ID. This authenticity check would make the data self-verifying to a greater extent.

This certainly seems like a useful bit of functionality that seems to dovetail with checking the hash chains. Feels symmetrical to check the hash chains for integrity of the data, and to check the signatures to verify the authenticity of the changes.

> However, one could also argue that signature checking does not need to be part of the Automerge core, and should be handled in a separate library layer.

I think this would make sense if the actor IDs were _not_ public keys which would push that concern up a layer, but if you decide to go with public keys, even building something on top of Automerge, I would expect that Automerge itself would do as much validation as it could.

**Comment by pvh** [comment]
I'm trying to think of an argument for why actors should not be Ed25519 public keys... They may become obsolete, which is a serious concern (see the Protocol Labs [multihash](https://github.com/multiformats/multihash) spec for a possible solution there.)

I think it's important to be cautious and thoughtful when selecting a key/hash/encoding but imposing a format might have significant storage benefits considering how frequently they're written.

I believe @HerbCaudill mentioned the current version of cevitxe uses GUIDs, which we have also used in past projects, and those are only 16 bytes vs a 256 bit Ed25519 key at 32.

That might be an argument for using a 16 byte actor ID and only writing the Ed25519 key on occasion. (It is hard to imagine a world in which the ~1e38 actors in a 128 bit space were insufficient...)

**Comment by ept** [comment]
Yeah, any system using cryptography needs cryptographic agility in order to switch to new algorithms as old ones are broken. This applies to the hash function just as much as the signature scheme. The Automerge binary format already has a version header, and I propose using this version number to determine the crypto algorithms in use. A version number bump would also allow the actorID length to be changed.

The main gotcha is: switching to a new crypto algorithm breaks compatibility with any collaborators who don't support the new algorithm. Thus, you have to first ensure that all collaborators are running a sufficiently recent version of the software, and then you can start using the new algorithm. We don't get the same kind of cross-version compatibility that we get for other aspects of the data format. But I think this sort of incompatibility is probably inevitable when it comes to algorithm changes.

Even if Automerge does not provide any signature checking itself, maybe it should provide space in the file format where signatures can be attached to the data? That would allow signatures to be stored along with the document, rather than in a separate file, which seems awkward.

**Comment by orionz** [comment]
My thoughts here ... 

Fixed Size ActorIDs:  While I have been one of the people asking you to give me fixed length actorId's so I can pack all my OpIDs and ObjectID's into flat arrays, at the end of the day I can achieve the same thing with a look up table and using internal indexes for this.  It's a ton more work but I don't want to see a non-optimal implementation for automerge based on saving me work.  I want automerge to be the best it can be.  That said - if we used 256bit actors - thats still 4x the size of a 64bit index and there could be considerable memory savings using a lookup table in large enough data sets even still...  

Crypto:  I love the idea of actorid's being public keys and signatures being checked by default - that said signatures are large and hard to compress and we've made such great gains in changes getting smaller.   For authenticating changes, thanks to the hash chaining, I believe we only need the final signature to verify.   The hash chains assure us the history has not been tampered with and we can assume that a signature on the 1000th change validates the 999 changes before it.   This lends itself to either automerge files having a sidecar signature file (which is akwayrd).. or signature blocks in the file that can be garbage collected.  Or an aggregate signature block at the end of the file that gets overwritten each time a new change is appended.  Also when syncing over the network since you would always be sending changes from some point in the hash-chain to the most recent change - you could just include that block of signatures at the end of each network message.  Given that there isn't a canonical network protocol yet its hard to say that this optimization would always work - but I think it has promise.   

I like it - I would love to see this in the protocol - we need to be smart to make sure this doesn't spoil the wonderful features of the current binary format, and I think we should do it even if we have many different sizes of actorID's and/or public key types to choose from.

If we supported several different crypto algorithms on day 1 then if there was an issue with an algorithm everyone could disable it and keep going without needing to release a different version of the software (similar to all those times we needed to disable SSLv? from the webserver and restart but it was fine b/c everyone already spoke TLSv?).

**Comment by aral** [comment]
Regarding cryptographic signatures… this would be very interesting. Unless I’m misunderstanding it, this would make Automerge akin to a JSON version of hypercore but with the huge additional benefit of also being a CRDT.

**Comment by ept** [comment]
@aral Yes, the hash chaining and signatures would be quite similar to hypercore. A difference is that a hypercore can only have a single author, whereas an Automerge document would support multiple collaborators, each with their own public key.

**Comment by ept** [comment]
I think I have come to the conclusion that it would not be desirable to bake a signature scheme into Automerge, because there are plenty of use cases for which they are not needed (e.g. apps that authenticate to a server with session cookies rather than client-side signatures), and they would add unnecessary overhead and complexity for these use cases. Also, we are not going to prescribe any particular format or length of actor IDs; from Automerge's point of view, actor IDs are just a sequence of bytes. If an application wants, it can use public keys as actor IDs, but this is not required.

Since hash chaining is baked into Automerge's data format, an application that wants to add signatures only needs to store the signature on the most recent change by each actor, which implicitly signs all the preceding change history. This should make signatures fairly easy to add in a separate library layer outside of Automerge core.
