### ISSUE TITLE
Cannot replace the property of an object nested within an array

### ISSUE THREAD

**Issue by nthnluu** [automerge/automerge#269]
I am receiving the error `Cannot assign an object that already belongs to an Automerge document. See https://github.com/automerge/automerge#making-fine-grained-changes` whenever I try to set a value of an object in an array. Here is the code I've been trying:

```
const doc1 = Automerge.from({
        "sections": [
            {
                "items": [
                    {
                        "answer_controller": [
                            {
                                "is_correct": false,
                                "content": [
                                    {
                                        "children": [
                                            {
                                                "text": "Answer Choice"
                                            }
                                        ],
                                        "type": "paragraph"
                                    }
                                ]
                            }
                        ],
                        "controller_type": "MC",
                        "question": [
                            {
                                "children": [
                                    {
                                        "text": "How many days are in a year"
                                    }
                                ],
                                "type": "paragraph"
                            }
                        ]
                        "id": "550979a3-1416-432c-aad5-e2a8a6f06cda"
                    }
                ],
                "id": "c6d735b8-2fe0-42e2-8d3a-493e0b1ef3b9"
            }
        ]
    })

<RichTextInput onBlur={(event) => event.target.value} initialContent={doc1.sections[0].items[index].question} />

const newDoc = Automerge.change(doc1, 'Update Item Content', doc => {
            doc.sections[0].items[itemIndex].question = newValue
        })
```
Apologies in advance if this isn't the correct way to do this. If this is expected, please let me know the recommended way to approach my problem. Thanks!

**Comment by ept** [comment]
Hi @nthnluu, sorry for the delayed reply. In your code, where does the variable `newValue` come from? Is it part of an existing Automerge document (perhaps the same document)?

What this code will do is to replace the entire question object, and all of its child objects, with a new object. This means that if two users concurrently update the same question, you will get a conflict, because Automerge will not be able to merge the changes, as documented in the README link that appears in the exception message. Is that what you intended?

If you really want to replace the whole question object, a workaround is to convert it to JSON and back:

```js
Automerge.change(doc1, 'Update Item Content', doc => {
  doc.sections[0].items[itemIndex].question = JSON.parse(JSON.stringify(newValue))
})
```

That will cause Automerge to forget that `newValue` came from an Automerge document.

**Comment by ept** [comment]
I think there is nothing more to be done on this issue, so I'm closing it. Please re-open if there is still a problem.
