### ISSUE TITLE
Automerge.Table merge leads to unexpected result

### ISSUE THREAD

**Issue by dehret** [automerge/automerge#271]
**Precondition**
Two clients (_Alice_ and _Bob_) both add items to an `Automerge.Table`. After that, they merge their changes (for the first time).

**Expectation**
I expect the `Automerge.Table` to contain all items added both by `Alice` and `Bob` after the merge.

**Actual behaviour**
Only the added items of one agent are kept. The items added by the other clients are discarded.

**Sample**
```
// Alice
let doc1 = Automerge.from({
  table: new Automerge.Table(),
});
doc1 = Automerge.change(doc1, "Adding a task", (doc) => {
  doc.table.add({ title: "Alice's item" });
});

// Bob
let doc2 = Automerge.from({
  table: new Automerge.Table(),
});
doc2 = Automerge.change(doc2, "Adding a task", (doc) => {
  doc.table.add({ title: "Bob's item" });
});

doc2 = Automerge.merge(doc2, doc1);

// Both Alice and Bob added an item, but after merging one of the added items is lost…
console.log(doc2.table.rows);
```

I assume this is due to issue #4 as both clients "concurrently" assign a new, empty Automerge.Table to the document's "table" key.

Is there a solution available that I could use to solve or work around this problem?

**Comment by ept** [comment]
Hi @dehret, you're right, this happens because Alice and Bob create two different table objects under the same key. We don't merge the contents of those objects, since doing so would lead to weird behaviour in different places.

You need to set things up so that the table is only created once. One way of doing this is for one of the users to perform the `Automerge.from()` initialisation, to share the document with the other user, and then both users can add items to the table:

```js
let doc1 = Automerge.from({
  table: new Automerge.Table(),
});
doc1 = Automerge.change(doc1, "Adding a task", (doc) => {
  doc.table.add({ title: "Alice's item" });
});

// Bob
let doc2 = Automerge.merge(Automerge.init(), doc1); // Alice shares her document with Bob
doc2 = Automerge.change(doc2, "Adding a task", (doc) => {
  doc.table.add({ title: "Bob's item" });
});

doc2 = Automerge.merge(doc2, doc1); // should now work as expected
```

If it is not possible to ensure that only one of the users creates the table, there is a more advanced trick you can use, but it requires some care. You can create a document with a constant actorId, perform the initialisation (i.e. table creation) using that actor, then create a separate document with a random actorId, merge the constant-actor document into the random-actor document, and then use the random-actor document from that point onward. This way, two different users that perform the same initialisation will use the same constant actorId, resulting in the exact same document being created, even though they did this independently. However, this requires that the initialisation steps performed using the constant actorId are exactly identical on each user. If there is any discrepancy, you will end up with permanently inconsistent documents.

Hope that helps; let me know if anything is unclear and I can elaborate.

**Comment by dehret** [comment]
Hi @ept, thanks a lot for your fast and helpful response!

I'd like two clients to being able to start working on their documents independently. And then sync up with each other at a later point in time. Given this use case, I don't think that I can ensure that the initialisation only happens on one client and is shared with the other client before the other clients start working on their document.

So I decided to try to implement the second workaround you described (even though it sounds rather scary to potentially end up in a permanently inconsistent state if the initialisation is messed up / different on the clients).

It does not seem to be working, though - most likely because I am doing something wrong. Here's what I tried:

```
const SHARED_INIT_ACTOR_ID = "init";
const sharedDocInit = () => {
  return Automerge.from(
    {
      table: new Automerge.Table(),
    },
    { actorId: SHARED_INIT_ACTOR_ID }
  );
};

// Alice
let doc1 = Automerge.init({ actorId: "alice" });
doc1 = Automerge.merge(doc1, sharedDocInit());
doc1 = Automerge.change(doc1, "Adding a task", (doc) => {
  doc.table.add({ title: "Alice's item" });
});

// Bob
let doc2 = Automerge.init({ actorId: "bob" });
doc2 = Automerge.merge(doc2, sharedDocInit());
doc2 = Automerge.change(doc2, "Adding a task", (doc) => {
  doc.table.add({ title: "Bob's item" });
});

// merge of both documents fails with "Error: Modification of unknown object"
doc2 = Automerge.merge(doc2, doc1);
```
Do you have an idea what I am doing wrong?

**Comment by ept** [comment]
Sorry, my mistake. This technique is supposed to work on the `performance` branch (which is working towards an Automerge 1.0 release), but I forgot that it doesn't work with the currently released version of Automerge due to the way object IDs are assigned. Here's a workaround that should work. Perform your initialisation once on your own machine:

```js
const INIT_DOC = Automerge.save(Automerge.from({table: new Automerge.Table()}))
```

Take this string and hard-code it into your application. Then, on Alice and Bob's devices, start a new document by loading that string:

```js
// Alice
let doc1 = Automerge.load(INIT_DOC);
doc1 = Automerge.change(doc1, "Adding a task", (doc) => {
  doc.table.add({ title: "Alice's item" });
});

// Bob
let doc2 = Automerge.load(INIT_DOC);
doc2 = Automerge.change(doc2, "Adding a task", (doc) => {
  doc.table.add({ title: "Bob's item" });
});

doc2 = Automerge.merge(doc2, doc1); // finally works!
```

**Comment by dehret** [comment]
Great, thanks so much, Martin!

Shipping the already initialised doc to each client actually makes more sense for this use case. It also means that I won't run into the issue you described (slight change in how the clients initialise the doc could lead to permanently inconsistent documents later on).

PS: I'm really looking forward for that 1.0 release - keep up the great work 👍
