### ISSUE TITLE
Automerge.from on a 10 MB JSON object takes 30 seconds, and Automerge.save produces a 70 mb string?

### ISSUE THREAD

**Issue by fasiha** [automerge/automerge#278]
I'm using Node 14.4 and Automerge 0.14.1. I have a moderately-complex object that, when JSON.stringify'ed to disk, weighs 10 MB. Running Automerge.from on it takes ~30 seconds. Then Automerge.save produces a ~70mb string (and takes ~6 seconds).

Is this normal, and Automerge isn't usable at these sizes? Or am I doing something wrong? I would naively expect the initial import to Automerge to be roughly the same size as the original object, but inspecting the output of Automerge.save, it looks like it's building the entire object as a series of insertions.

Demo repo: https://gist.github.com/fasiha/d24aec8ebeaa770bfe48ac5a9265c838 (the JSON is pretty-printed so it's 15mb, without extra whitespace it's ~10mb; GitHub just shows the top few thousand lines, if you clone the repo and run `demo.js`, it'll print this info).

**Comment by bennetthardwick** [comment]
From my understanding, Automerge adds a bunch of metadata to allow concurrent editing. You're essentially paying for these features, so when designing your data structure you should only include things in Automerge that multiple people would edit or that users could edit.

In your data, you've got stuff like "sha1" which probably won't be edited by anyone. Likewise, a lot of the output seems like it's computed from MeCab or something like that, maybe you could store just the text (that would be edited by multiple people) and run and cache the MeCab output outside of automerge?

There's some work being done at the moment on a "binary format" for Automerge which will help with the file size (#253) so that could help, but I think only using Automerge for data that will be edited by multiple users is the way to go in the long run.

Hope that helps! :smile:

**Comment by fasiha** [comment]
That helps, thank you. I didn't appreciate that collaboratively editing *an object* is fundamentally different than collaboratively editing text.
