### ISSUE TITLE
[QUESTION] Shouldn't the type of the snapshot be a FrozenObject?

### ISSUE THREAD

**Issue by fedekau** [automerge/automerge#295]
Hi 👋  Great job on this library! I am new to the topic and I am working on a proof of concept using TypeScript and I think I found something inconsistent, but since I am pretty new to the CRDTs and the library itself I just want confirmation from someone with more experience 😄 

Im trying to grab a specific version of a document (snapshot) for users with a different role, basically I want admins to see the latest version and the other users see the latest published version.

The problem I am facing is with types, I would expect that the `doc` and `snapshot` variables in the code below have the same type, but they don't.

```ts
const doc = Automerge.change<T>(...) // This returns a FrozenObject<T>
const history = Automerge.getHistory(doc);
const snapshot = history[history.length - 1].snapshot // This returns a T
```

Is the difference in types the intended behavior? 

Thanks!

**Comment by dan-weaver** [comment]
Yeah it’s intentional it seems. They’re different things.  

The returned type from ‘change’ is is an altered automerge doc that you can, in your example, call getHistory on.  You could also call pass it to other methods of Automerge such as ‘getChanges’, ‘merge’, ‘diff’ etc.  Because it’s type represents an Automerge document.  If you look at the type declarations you’ll see that ‘Doc’ is a actually an alias for FreezeObject.

A snapshot is just a flat object representation of the contents of the document at a particular point in the history.  And cannot be used as a proper Automerge document.

hope that helps.

**Comment by fedekau** [comment]
@dan-weaver Thanks for the answer, that makes sense!
