### ISSUE TITLE
receiveSyncMessage is not invoking patch callback

### ISSUE THREAD

**Issue by nemanja-tosic** [automerge/automerge#349]
Expected: patchCallback should be invoked, as the document is being patched.

**Comment by nemanja-tosic** [comment]
Might have jumped the proverbial gun here. Will close if i did.

**Comment by ept** [comment]
Hi @nemanja-tosic, if you pass a patchCallback when the document is instantiated (i.e. on `Automerge.init()`, `Automerge.load()`, `Automerge.from()`, or `Automerge.clone()`), then that callback should get called on `receiveSyncMessage`. I didn't include an options object for `receiveSyncMessage` since the function actually returns the patch as its third return value, which gives you the same information without the clumsy control flow of a callback function.
