### ISSUE TITLE
faster `doc.text()`

### ISSUE THREAD

**Issue by orionz** [automerge/automerge#363]
The upwelling team has noted that `doc.text()` takes 10-20ms for large documents and their app calls it several times on a single page refresh which adds up.  They are currently mitigating it by memoizing the function but worry about bugs and knowing when to clear the cache.  Seems to me we could make this very fast for them.   I see two ways to go about this.  

The simple way would be to store an `Option<String>` on each OpTree and do the memoizing ourselves.  Clear it when ops are inserted into the tree and store it when `doc.text()` is called.  The first call will take 10-20ms and the following calls will be fast, until the text is changed.   This is nice b/c it will not slow down local or remote edit ops at all - but its bad as it has to do a full op tree walk to compute a text value once, each time the text is upated.

The other way to do it would be to store a rope on the OpTree.  When a char is inserted or deleted - update the rope.  Local ops will always be fast since we know where in the rope to update.  Remote ops will be a little slower since they will need to compute the visible index when inserting and consider conflicts.  Overall it will add a tiny tax to local ops, a larger tax to remote ops, but will make `doc.text()` always very fast. 

Thoughts?

**Comment by ept** [comment]
I don't know the codebase well so I'm not really in a position to comment. Just a question: is it really desirable to be fetching the entire text every time the document is updated? My understanding of text editors was that they are not really designed to have their entire content replaced on every keystroke, but rather that it's better for a keystroke to make the minimal necessary update to the text editor state (inserting or deleting only the specific characters that were changed). We ran into this with Peritext, where we found that replacing the entire doc in ProseMirror is not good, because it messes up annotations in the document (e.g. search result highlighting), and it's slow. So I'm wondering whether calling `doc.text()` frequently is actually a design smell, and rather than making the function faster, we should be changing the app to call that function less often.

**Comment by alexjg** [comment]
Is this something which needs to know about automerge internals or is it something that could be implemented in a wrapper library (that mystical beast we all speak of but which no one has glimpsed, except dimly in their dreams)? My reason for asking is that as a low level library - especially one intended for FFI based interop - the memoization tradeoff seems to me like something we don't want to force on users.

I suppose the main thing a wrapper library would struggle with here would be distinguishing between the local and remote cases - i.e. a wrapper library would always have to pay the remote op cost?

**Comment by okdistribute** [comment]
FWIW, blaine's implementation isn't replacing the prosemirror state fresh every time. Upwelling calls `doc.text()` because

* to pick out what was changed from the attribute call. and convert it from prosemirror to automerge https://github.com/inkandswitch/upwelling/blob/56fa6fcccde54d611bc7a7d45eb6672f643a60e1/app/src/prosemirror/utils/AutomergeToProsemirrorTransaction.ts#L17
* relatedly, to identify if there is a block for the changes pugin https://github.com/inkandswitch/upwelling/blob/86ea06734b852b43ae02b137af82e5f1639c1156/app/src/prosemirror/AutomergeChangesPlugin.ts#L28
* to know the objID of the text document to know when the text changed  https://github.com/inkandswitch/upwelling/blob/56fa6fcccde54d611bc7a7d45eb6672f643a60e1/api/src/RTC/RTCDraft.ts#L32

**Comment by okdistribute** [comment]
We also have a cache for attribution calls: https://github.com/inkandswitch/upwelling/blob/edd91714bff1f0b534b576f8c56e21d518ff77c8/api/src/Upwell.ts#L107-L114

**Comment by jeffa5** [comment]
Is it possible to extract a benchmark for this so that we can profile it to see where the time is being spent? I think we could optimise the `ListVals` query in the Rust/wasm side but would want to know that is where the time is spent (and the benchmark is useful for catching regressions).

**Comment by orionz** [comment]
PR #572 is running doc.text() now in 2ms
