### ISSUE TITLE
Granular merging of nested objects

### ISSUE THREAD

**Issue by baiirun** [automerge/automerge#549]
How do we granularly merged deeply nested objects without having conflicts on the entire object?

This isn't the greatest example but hopefully the idea gets across.

```ts
type Fruit = { id: string, type: "banana", bananas: { ripeness: number }[] }

type FruitBasket = {
  fruit: Record<string, Fruit>
}


function addFruitToBasket(newFruit: Fruit) {
  let doc1 = Automerge.change(Automerge.init(), doc => {
    fruit: {}
  })

  doc1 = Automerge.change(doc1, doc => {
    fruit[fruit.id] = newFruit
  })
  
  return doc1
}

function addSecondFruitToBasket(newFruit: Fruit) {
  let doc2 = Automerge.change(Automerge.init(), doc => {
    fruit: {}
  })

  doc2 = Automerge.change(doc2, doc => {
    fruit[fruit.id] = newFruit
  })
  
  return doc2
}

const fruitBasket1 = addFruitToBasket({ id: "1", { type: "banana", bananas: [{ ripeness: 5 }] })
const fruitBasket2 = addSecondFruitToBasket({ id: "1", { type: "banana", bananas: [{ ripeness: 3 }] })
const mergedFruitBasket = Automerge.merge(Automerge.clone(fruitBasket1), Automerge.clone(fruitBasket2))
// mergedFruitBasket -> { 1:  { id: "1", { type: "banana", bananas: [{ ripeness: 3 }] } }
```

`mergedFruitBasket` in the example merges to `{ 1:  { id: "1", { type: "banana", bananas: [{ ripeness: 3 }] } }` when I'd expect it to merge to `{ 1: { id: "1", { type: "banana", bananas: [{ ripeness: 3 }, { ripeness: 5 }] } }`.

If this example is a little too convoluted I can try and make a simpler one. Is there a way to avoid conflicts if I need to completely reassign some nested object?

If I understand correctly, Automerge won't be able to merge this because there's two different operations on the same object, so it randomly chooses a winner?

**Comment by alexjg** [comment]
What you have run into here is what we have been referring to as the "initial data problem".  The problem is that individual objects within automerge have their own identity. In the example you are using the two documents independently create a map object under the `.fruit` key of the root map. These two objects have their own identities and so automerge sees two operations:

1. set the `fruit` key of the root map to `<new map ID on doc1>`
2. 1. set the `fruit` key of the root map to `<new map ID on doc2>`

like any other set operation these are then seen as conflicting (consider if you had just set the `fruit` key to a string in each document).

The solution to this problem for now is to create a skeleton document which contains the top level keys you know you need and ship it with your app. 

E.g. 

```javascript
let initDoc = Automerge.save(Automerge.from(fruit: {}))
// Now base64 encode the init and bundle it in your app
```

Later on in the app startup

```javascript
let doc = Automerge.load(<the bundled skeleton doc>)
```

Now, this is a bit irritating and so we're thinking of changing the way conflicting object properties are handled https://github.com/automerge/automerge/issues/528

**Comment by baiirun** [comment]
Awesome, thanks for the workaround! I'll give it a try.
