### ISSUE TITLE
performance characteristics of automerge

### ISSUE THREAD

**Issue by epikhighs** [automerge/automerge#59]
Hi,

**preface**
I've wanted to introduce immutable.js to my app, but I disliked having to use the immutable.js data structure's API (e.g. using .get() instead of just accessing a property on an object).  Now, I'm thinking that automerge might be able to give me the best of both worlds by providing immutable data that uses just plain javascript objects and arrays.

**question**
I was curious about the performance implications of using automerge in my redux app. I know that Immutable.js has some optimizations for operating within it's data structures (e.g. adding to an immutable.js List), but I've read that there's a performance hit for converting an immutable.js data structure into a vanilla javascript object or array (e.g. using the .toJS()).  How does automerge keep operations on large data structures (e.g. a giant redux state tree) performant?  Also, are there any other performance characteristics I'd need to keep in mind when using automerge?

Thanks.

**Comment by ept** [comment]
Hi @epikhighs, thanks for your interest!

Automerge is primarily about allowing several users to collaborate on a data structure, and it's only incidentally an immutable data structure library. So if you're only building a single-user app, there is not much point in taking on the overhead of Automerge. As alternative, take a look at [immer](https://github.com/mweststrate/immer), which provides an API similar to `Automerge.change` for single-user data structures.

As to the performance cost, it's a bit hard to answer in general, since different data structures have different costs. I suggest you try it with the kind of data you have in mind, measure the performance, and if it's not good enough, let us know so that we can try to make it better :)
