### ISSUE TITLE
Calling `getHeads` on a `PatchInfo.after` document error

### ISSUE THREAD

**Issue by acurrieclark** [automerge/automerge#593]
The `getHeads` call in the following code throws a `recursive use of an object detected which would lead to unsafe aliasing in rust` error. This is with Automerge `2.0.3`.

```ts
const doc = init<{ count: number }>();

const newDoc = change(
  doc,
  {
    patchCallback: (_, patchInfo) => {
      const heads = getHeads(patchInfo.after); // => error: recursive use of an object detected which would lead to unsafe aliasing in rust 
    },
  },
  (doc) => {
    doc.count = 1;
  },
);

getHeads(newDoc); // <= this works without issue
```

I am aware that `PatchInfo` also contains a `to` property which contains the heads, but I would expect the `after` document to be a fully usable document, which could be passed outside the callback.

**Comment by alexjg** [comment]
The issue here is that  we are violating Rusts borrowing rules in the implementation of `automerge_wasm::Doc::apply_patches`. Here's the sequence of events:

1. After having made a change in JS in `change` we call `automerge_wasm::Doc::apply_patches` to apply any patches which were generated by the change to the JS state of the document
2. `apply_patches` calls the patch callback, passing the before and after states, which are instances of `Automerge.InternalState`. 
3. The patch callback then calls `automerge_wasm::Doc::get_heads` on `after.handle`, which is the same pointer we passed to `apply_patches`. This violates rusts borrowing rules - which are enforced at runtime by a `wasm-bindgen` equivalent of `RefCell` - causing a panic.
4. We catch the panic in the `try ... catch` in `_change` and attempt to call `automerge_wasm::Doc::rollback` to undo any chances which were made. `rollback` attempts to borrow the `Doc` pointer, but due to the panic it's guard was never dropped and so wasm-bindgen still considers it in use, which causes it to panic again on the rollback.

Note that this doesn't happen with `PatchInfo.before` because the heads are cached on the JS side.

In this particular case the problem can be solved by using the `PatchInfo.to` field to get the heads afterwards, rather than using `getHeads(patchInfo.after)`.

In general though, it is not safe for us to be passing the document handles into the patch callback, and in fact it's not safe to interact with the document at all in the patch callback. There are two ways I can see around this:

1. Clone the before and after states before passing them into the callback. This would probably destroy performance and so would be something we would want the user to opt into. 
2. Run the patch callback in JS and not in WASM and use `automerge.view` to generate a cheap view of the document before and after for the callback.

I'm going to have a crack at 2 first.


the patch callback is called by `automerge_wasm::Doc::apply_patches`. This method takes a mutable reference to the document being modified, which is the same reference we then pass to the patchcallback as `PatchInfo.after`. The call to `getHeads` then makes a call to `automerge_wasm::Doc::get_heads`, but the reference we pass to `get_heads` is already borrowed by the `apply_patches` call and the wasm bindgen wrapper panics because we're violating rusts aliasing rules.

The panic

**Comment by acurrieclark** [comment]
So in the `automerge-repo` use case, where we are looking to pass the `after` document out into the world as the new version of the document, it sounds like it might not be practical either way?

I think it's incredibly useful having the before and after states (I am currently using if for undo/redo, for example) but if `after` can't be treated as the full document we might need to rethink.

**Comment by alexjg** [comment]
I am hopeful we can maintain the same API but we shall see
