### ISSUE TITLE
Automerge.save does not persist orphan changes, potentially leading to a loss of convergence

### ISSUE THREAD

**Issue by federico-terzi** [automerge/automerge#595]
Hey folks!

First of all, Automerge is amazing, thank you for all your hard work and the commitment to making it open source!

I've been playing with it for an upcoming application I'm working on, and I've encountered a non-intuitive behavior, which might be considered a bug:

> It seems like "orphan" changes are not persisted with `Automerge.save`, is it an expected behavior?

I've put together a small example (also available on [Stackblitz](https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-btubxh?file=index.js) for easy testing, just run `node index.js` in the terminal):

```js
const Automerge = require("@automerge/automerge");
const { createHash } = require("node:crypto");

function sha256(content) {
  return createHash("sha256").update(content).digest("hex");
}

let doc1 = Automerge.init();

doc1 = Automerge.change(doc1, "first change", (doc) => {
  doc.field = "one";
});

let doc2 = Automerge.init();
doc2 = Automerge.merge(doc2, doc1);

doc2 = Automerge.change(doc2, "second change", (doc) => {
  doc.field = "two";
});

const secondChange = Automerge.getLastLocalChange(doc2);

doc2 = Automerge.change(doc2, "third change", (doc) => {
  doc.field = "three";
});

const thirdChange = Automerge.getLastLocalChange(doc2);

console.log("doc1", doc1, sha256(Automerge.save(doc1))); // doc1 { field: 'one' } 614f96017f9cbe826d893d5a2c41251697e5e5bb9b63d2cea3c75ecdf84dbb42
console.log("doc2", doc2, sha256(Automerge.save(doc2))); // doc2 { field: 'three' } f0ac3f0046407885f4984d2b98da735668031f0d3fbaf9a247633061fd0b0ec2

console.log("now we apply the third change");
[doc1, patch] = Automerge.applyChanges(doc1, [thirdChange]);

// Here I would expect the saved Hash to be different, as we added the third change
console.log("doc1", doc1, sha256(Automerge.save(doc1))); // doc1 { field: 'one' } 614f96017f9cbe826d893d5a2c41251697e5e5bb9b63d2cea3c75ecdf84dbb42

// This causes a non-intuitive difference in behavior if we load the documents from persistence

let persistedDoc1 = Automerge.load(Automerge.save(doc1));

console.log("now we apply the second change");
[doc1, patch] = Automerge.applyChanges(doc1, [secondChange]);
[persistedDoc1, patch] = Automerge.applyChanges(persistedDoc1, [secondChange]);

// In theory, I would expect the two to be equal, as both persistedDoc1 and doc1 have been applied the same changes
console.log("doc1", doc1, sha256(Automerge.save(doc1)));  // doc1 { field: 'three' } f0ac3f0046407885f4984d2b98da735668031f0d3fbaf9a247633061fd0b0ec2
console.log(
  "persistedDoc1",
  persistedDoc1,
  sha256(Automerge.save(persistedDoc1))
);  // persistedDoc1 { field: 'two' } 24ff50608b01fcd094118c0a3b3ceabf701b34c0fcf3a1213b0eb71747973679
```

In the example above, I would expect both `doc1` and `persistedDoc1` to have the same content, as they've both encountered the same changes (third and second), despite being out of order.

I might be missing something, but I think this should be considered a bug as it invalidates the convergence guarantee from the [docs](https://automerge.org/docs/cookbook/real-time/#changes-interface) when dealing with persisted/saved documents:

> The counterpart, Automerge.applyChanges(oldDoc, changes) applies the list of changes to the given document, and returns a new document with those changes applied. Automerge guarantees that whenever any two documents have applied the same set of changes — even if the changes were applied in a different order — then those two documents are equal. That property is called convergence, and it is the essence of what Automerge is all about.

Thoughts? 

I'm running the latest released Automerge version: 2.0.3

Again, thank you for all your hard work! And if I can help further in some way, just let me know

**Comment by ConradIrwin** [comment]
There is a known issue around this, and as you observed the problem is that when you save a doc it does not persist changes unless all their dependent changes are present.

The technical reason for this is that when the document is compressed the file format stores dependant changes by reference (not by full change hash).

There are probably two ways forward:
* Make this behaviour much clearer in the documentation.
* Handle this case by appending any orphaned changes as change chunks after the document chunk when `save` is called.

Out of interest, how did you end up in this situation? 

The assumption is that mostly you'll get changes in dependency order and so this should be a rare/non-extant occurrence, but it could be that that assumption is not valid.

**Comment by alexjg** [comment]
@orionz and I were having a chat about this and we think it makes sense to just append the orphaned changes to the saved document chunk. This does raise an issue where you could end up with a large number of orphaned changes which you never receive the dependency for so we may also need to add some APIs for removing orphaned changes explicitly.

**Comment by federico-terzi** [comment]
@ConradIrwin @alexjg Thanks for replying!

> @orionz and I were having a chat about this and we think it makes sense to just append the orphaned changes to the saved document chunk.

Sounds like a good approach! 

Do you think the format would still be byte-by-byte identical in the case of concurrently serialized documents with the same changes? I'm asking this question because one of the very nice properties of automerge I've stumbled upon (maybe it's an incorrect assumption?) is that if two documents have the same set of changes, then their serialized blob is identical (using `save`).

This is extremely helpful at the application/storage layer, as there are scenarios where an application might simply compare the blob (or a hash of it) to make sure two documents are identical, without loading the automerge document into memory.

That would probably require appending changes in a deterministic and convergent order

> Out of interest, how did you end up in this situation?

I'm designing an application where multiple channels could be used concurrently (from different peers) to sync changes. As you suggest, in most cases the order would follow the dependency order, but there are times when changes are relayed/proxied by other nodes, and we lose that delivery guarantee.
If everything was happening only in memory that would be fine (as Automerge documents do keep orphaned changes in memory), but the system is periodically serializing the documents to persistent storage to allow the application to go offline and be closed (The good news is that the system, if properly designed, would "heal itself" at some point with the other peers sending the missing information, but still, the current behavior of `save` would be less than ideal)

If there is anything I could do to help, just let me know :) Thanks for the hard work!

**Comment by alexjg** [comment]
> Do you think the format would still be byte-by-byte identical in the case of concurrently serialized documents with the same changes? 

This is a good point. Provided we encode the changes in a deterministic order then yes, they would be byte for byte identical. I suppose the ideal order would be topographical, but this would be a partial order because there are missing dependencies and so to avoid complexity I think we could just go for lexicographic order of the change hashes.

**Comment by ept** [comment]
> I'm asking this question because one of the very nice properties of automerge I've stumbled upon (maybe it's an incorrect assumption?) is that if two documents have the same set of changes, then their serialized blob is identical (using save).

Unfortunately I don't think that's true, although it would be possible to make it true. The document contains a list of changes that were applied to it, and AFAIK this list is stored in the order in which the changes were received. If two instances of a document receive changes in different orders, their user-facing document contents will be the same, but the encoded documents will not, because the internal list of changes is reordered. To make the encoded documents identical, all instances of a document would have to store that list in a deterministic order. That seems doable, but I don't think the implementation does it right now.

Another stumbling block to byte-identical documents is that the DEFLATE compression is not guaranteed to be deterministic (it's possible that the particular implementation we're using is deterministic, but it could change from one version to another).

I also think that it would be nice if encoded binary documents were convergent, and in most ways the encoding format does provide the necessary determinism. Those two issues are the only things I'm aware of that prevent `save` output from being identical.

**Comment by federico-terzi** [comment]
@ept @alexjg Thank you guys, very interesting insights!
