### ISSUE TITLE
Investigate switching to `Rc` in `PatchLog` so that `AutoCommit` is `Send` again

### ISSUE THREAD

**Issue by alexjg** [automerge/automerge#681]
We used `Rc` because the patch log is on the hot path for patch generation and we were concerned about performance. But making `AutoCommit` `!Send` is a pretty severe usability fail so we should benchmark whether `Arc` is much slower and switch if not.

**Comment by aran** [comment]
I have some prototype code using AutoCommit as Send, which breaks on upgrade from 0.4.1 -> 0.5.0 as a result

**Comment by aran** [comment]
If `Send` can be a part of the API that would be great. Maybe the order of operations in this issue can be switched. Instead of blocking on a benchmark, switch to Arc now, for ergonomics. Then later as a potential optimization, benchmark the benefit of pure `Rc` to measure the improvement achievable through that.

**Comment by orionz** [comment]
Yes. We should switch to Arc now.  The Rc is internal only so we can optimize it later (if it becomes an issue)

**Comment by alexjg** [comment]
I'll publish a new crate version later today once I've got a few other changes in.
