### ISSUE TITLE
undefined value throws RangeError: Field name does not exist exception

### ISSUE THREAD

**Issue by danielwii** [automerge/automerge#78]
```javascript
let autoFields   = autoMerge.init();
autoFields       = autoMerge.change(autoFields, 'v0-init', (doc) => {
  doc.fields = { name: undefined };
});
```
throws `RangeError: Field name does not exist: name`
[runkit](https://runkit.com/danielwii/5ab7787466ea700012ecbee8)

**Comment by ept** [comment]
Thanks for your report, @danielwii. Automerge doesn't support the use of `undefined` in data, since it doesn't exist in JSON. Please use `null` instead.

I have made a change f7e739aa992f060f100cdf1c96d83c5e7264db83 so that Automerge throws a more helpful error message when an unsupported datatype is used.
