### ISSUE TITLE
What's the difference between loadIncremental and applyChange?

### ISSUE THREAD

**Issue by iamwilhelm** [automerge/automerge#783]
The UInt8Array produced by `getLocalChanges()` and `saveIncremental()` seem to be different, so that I can't apply the UInt8Array produced by `getLocalChanges()` to `loadIncremental()` and vice versa. What's the difference between the two, and do you use them in different situations or instances?

To my knowledge, `saveIncremental` keeps track of the last head that you called it for a particular document, and `getLocalChange` only get the operations for the last head?

**Comment by orionz** [comment]
`Automerge.getChanges()` and `Automerge.getLastLocalChange()` give you one or more changes encoded as Uint8Array's.   These changes can be used in `Automerge.applyChanges()` and `Automerge.decodeChange()`.  These can be useful if you're manually managing the flow of changes but generally you'd want to use sync messages or save/saveIncremental for that.

If you're progressibly saving to a single file with a single writer.   Doing a `Automerge.save()` to create the file and then periodically calling `Automerge.saveIncremental()` and appending the results to that file will give you a file you can later load with `Automerge.load()`.   This file will grow pretty large over time and doing a new `Automerge.save()` will give you a much smaller document and you start appending the incremental chunks again.  The data returned by `save()` is a special compressed full document file.  `saveIncremental()` returns the same changes that `getChanges()` and `getLastLocalChange()` does but they are app appended together instead of broken apart into indivual objects.  The `loadIncremental()` method will happily consume all 3 types of object appended together in any order and with any amount of duplication. 

Storing the `getHeads()` after save, then calling `getChanges(lastHeads)`, concatenating the changes together and updating lastHeads will functionally give you the same data `saveIncremental()` returns. 

For keeping documents in sync you need `generateSyncMessage()` and `receiveSyncMessage()` which produces a set of changes with a bunch of additional metadata to allow the peer to not overshare.  For very simple setups you can (but it is not recommended) set up systems where you call `getLastLocalChange()` after every change and broadcast them to all other documents, or have one document passively mirror another by just consuming it's `saveIncremental()`.

**Comment by iamwilhelm** [comment]
Thanks for your quick reply. I have some follow ups:

> The loadIncremental() method will happily consume all 3 types of object appended together in any order and with any amount of duplication. This means you can $ cat docA docB > docC and then load docC and get the merge of docA and docB.

So given that you unwrap the Change[], you can just smash them all next to each other, in whatever order, with any dups, and `loadIncremental()` will be able to consume them all? even if these changes are from different clients? I assume yes, since the UInt8Array is just a binary encoded version of Patches, and there's some sort of clock on each Patch to order them all. 

Would you be able to loadIncremental() these concatted changes multiple times? Is it idempotent, or would it just error out? Or would it just pick up the changes it didn't have and just ignore all the changes that it does?

Lastly: To sync docs, there's a few ways:

If you have the entire state of two docs available to you locally, then you can just use `merge()`

If you just have one doc locally, the other client can send its changes to you. The other client can either:
- use `getLastLocalChange()`, assuming that it's sending that to you on every change, and the network is robust.
- use `getChanges()`, assuming the other client is keeping track of the last head it sent you, and if there are changes that you already consumed, it's idempotent.
- use `saveIncremental()`, if the other client wants the last head sent kept track of for it, and when you receive these string of changes, and if applied locally are idempotent.
- use `generateSyncMessage()`, if the other client also doesn't want to overshare and don't want to keep track of the last head, so I assume, it will generate a different sync message for every client. and when you receive these string of changes, if applied locally will be idempontent.

Is that a good summary?

If it missed one, then you'd have to keep waiting until you got the missing one to proceed (since this is op-based CRDT).

**Comment by alexjg** [comment]
> So given that you unwrap the Change[], you can just smash them all next to each other, in whatever order, with any dups, and loadIncremental() will be able to consume them all? even if these changes are from different clients? I assume yes, since the UInt8Array is just a binary encoded version of Patches, and there's some sort of clock on each Patch to order them all.

Yup you can load them in any order

> Would you be able to loadIncremental() these concatted changes multiple times? Is it idempotent, or would it just error out? Or would it just pick up the changes it didn't have and just ignore all the changes that it does?

It's idempotent yeah, it would just ignore everything it already has.

Your summary of sync options is good but there's also [saveSince](https://automerge.org/automerge/api-docs/js/functions/next.saveSince.html) which allows you to save everything since some heads and then send it to the other end to load with `loadIncremental`.
