### ISSUE TITLE
Can (should?) we merge only the "end result" of an "edit-branch" into a doc, discarding the full edit history?

### ISSUE THREAD

**Issue by Sjoerd82** [automerge/automerge#789]
I'm trying out Automerge, and am quite excited about its potential. I forsee using it in various scenarios in my application. Starting with the least collaborative, one is where the user has a form with a save and discard button (perhaps a bit of an edge-case in the collaborative landscape). In which case we start with an original `doc`. I don't want to mutate this doc, because the changes to it could be discarded by the user, I therefore make a clone `docEdit`. 

```js
// doc contains the current state for this client.
// let's create a "branch" for (potential) changes.
let docEdit = A.clone(doc)
// "Edit-mode" now starts, and docEdit is (potentially heavily) mutated.
// All changes are tracked, and we could maybe even enjoy doing undo.
// That's nice for the editing session, but considered waste once the user finishes editing.
```

If at this point the user decides to discard his changes, we simply ingore docEdit, and move on. Fine.

If at this point the user clicks save, I'd ideally not have the full changelog merged into the doc, but only the resulting changes; for example, if a user has clicked the same checkbox 11 times on/off, I rather only record the final state. Same goes for text editing, once done editing, I don't need a record of every change, but only the difference between before and after.

```js
doc = A.merge(doc, docEdit) // I think this will store the FULL edit log of all of the changes made by the user. Correct?
```

I do realise that in a "live"-collaboration environment you will probably want to catch all the changes, but this is a less "lively"-part of my application, if that makes sense.

Alternatively, I guess I could do a diff between the before and after object, and "manually" apply all the changes to `doc`.

I literally just started, so I may be a bit ignorent in the ways of AutoMerge. ;-)

**Comment by alexjg** [comment]
This idea of only merging the final state of a set of changes is something we don't yet support but we want to. It relies on being able to say something like "this sequence of changes which I am not sending you is equivalent to this other change". This primitive also allows us to do various other useful things like compacting history which no one cares about any more.

There is a slightly more complex flavour of this which we also aim to support which is where you wish to keep the intermediate changes around  but only sync them with some peers and with others you sync the "shortcut" change. One (real, based on user research) scenario where you might want to do this is if you are a team of lawyers collaborating with your colleagues - whom you trust - and an opposing team of lawyers - whom you do not trust. In this case you would wish to keep the history of all changes when syncing with your colleagues so that you can get all the nice features of a full-fat history (time travelling, undo, the ability to merge with peers who were offline during the shortcut) but only send the final version to your adversaries. 

Anyway, all this is to say that this is an area we are actively researching and will be implementing features to support. Right now however, you can't do it natively. However, you can use `diff`. What you would do is create a clone of the document you are merging into and then merge the document you wish to save into the cloned document. At this point you have a clone of the original document which contains all the changes from the branch. Then you would call `Automerge.diff(original, updated)` to get a patch which describes the difference between the two. You would then walk through the diff applying the patches to the original document.

This is quite manual right now but I am aiming to add an `applyDiff` function or similar to do it for you.

**Comment by Sjoerd82** [comment]
Not a real big deal; for now I'll simply handle this manually. It's nice to see that these things are still actively being researched and pursued. Thanks for the in-depth explanation. I'll mark this as closed then.
