### ISSUE TITLE
Automerge.change()'s patch callback returns patches that might no-op (but `diff()` does not)

### ISSUE THREAD

**Issue by stephen** [automerge/automerge#802]
Sample code:
```js
const Automerge = require("@automerge/automerge");

let doc = Automerge.from({ entries: {} });
doc = Automerge.change(
  doc,
  { patchCallback: (patches) => console.log(patches) },
  (doc) => {
    doc.entries["1"] = { hi: 0 };
    doc.entries["1"] = { hello: 0 };
    delete doc.entries["1"];
    doc.entries["2"] = { goodbye: 1 };
  }
);

// output:
// [
//     { action: 'put', path: [ 'entries', '1' ], value: {} },
//     { action: 'put', path: [ 'entries', '1' ], value: {} },
//     { action: 'del', path: [ 'entries', '1' ] },
//     { action: 'put', path: [ 'entries', '2' ], value: {} },
//     { action: 'put', path: [ 'entries', '2', 'goodbye' ], value: 1 }
// ]

Automerge.diff(doc, [], Automerge.getHeads(doc));
// output:
// [
//     { action: 'put', path: [ 'entries' ], value: {} },
//     { action: 'put', path: [ 'entries', '2' ], value: {} },
//     { action: 'put', path: [ 'entries', '2', 'goodbye' ], value: 1 }
// ]
```

Note that in the first output, the `entries.1` path is put twice then deleted, i.e. could have skipped altogether.

It was unclear to me if this behavior was expected or not, so I figured I'd report the discrepancy.

**Comment by alexjg** [comment]
Yeah we don't make much effort to make the patches produced during the `change` callback minimal. We have to produce patches as the changes occur anyway because that's how we make the change to the materialized view which is used during the callback (the `doc` in `(doc) => ...`) so it's cheapest to just return those same patches to the patch callback. On the other hand in `diff` we're having to produce patches from scratch anyway and it's often worth compressing the patch a little.

In general there are no guarantees given about the patches except that applying them will leave you with a materialized view of the state. In particular we don't try and produce minimal patches and we don't try and produce patches which have any kind of one-to-one correspondence with specific changes.

**Comment by stephen** [comment]
Makes sense - thanks for the explanation!
