### ISSUE TITLE
Why can't keys be empty?

### ISSUE THREAD

**Issue by joshuahhh** [automerge/automerge#852]
Per [1], keys can't be empty strings in Automerge maps. I've run into a situation in the wild where my JS data naturally contains the empty string as a key, so this will be a bit awkward to work around.

I'm curious if there's a reason Automerge excludes `""` as a key, or if this is just a provisional decision.

(Thanks!)

[1] https://github.com/automerge/automerge/blob/a0ac03edd4c73b78ee3e1bf3b4583bc16804232f/rust/automerge/src/transaction/inner.rs#L419

**Comment by joshuahhh** [comment]
FWIW, in JS "All String and Symbol values, including the empty string, are valid as property keys." (https://262.ecma-international.org/6.0/#sec-object-type). I know this isn't determinative for Automerge, but it seems like a nice model to follow if possible.

**Comment by cristianmadularu** [comment]
We ran into a similar issue and, while not a real fix, we used this fast-clean library to 'clean' null/undefined/empty strings values from our objects before storing them in automerge.
https://github.com/Youssef93/fast-clean

I know that it may not be the most elegant solution, but it worked for us :).

**Comment by ept** [comment]
It's been a long time since I added that check for nonempty keys, but IIRC I was worried about cross-language compatibility. Even if JS allows empty strings as property names in an object, other languages may not, and we want Automerge to smoothly interoperate across languages and platforms (this is also the reason why `undefined` is not allowed). A secondary reason was that it might be useful for future extensibility of Automerge if there is one key that applications may not use, because then it could be used for some Automerge-internal (as yet undetermined) purpose in the future.

Both of those arguments are somewhat weak – the might be other keys (say, strings containing spaces or even weird Unicode stuff) that are allowed by Automerge, but that are not valid object properties in some languages. And the extension mechanism may never be needed, as the Automerge binary data format also has several other extension points that will probably be sufficient. So I think it would be okay to relax this constraint and allow empty strings.

**Comment by kid-icarus** [comment]
For what it's worth, all the existing Automerge implementations support empty strings as hashmap keys:

- Swift
- Golang
- Rust
- JS
- Python
- Java

I'm actually curious which languages forbid empty strings as keys 🤔

**Comment by savaki** [comment]
Wouldn't that also imply the language wouldn't be able to decode from json seeing as json supports the empty string?
