### ISSUE TITLE
proposal: allow underscores

### ISSUE THREAD

**Issue by rikkertkoppes** [automerge/automerge#94]
Currently underscores are not allowed in documents. This is unfortunate as it makes automerge less universal.

I understand this is to prevent accidental overwrites of tracking props, such as _actorId, _objectId, _conflicts and _state. When adding automerge to an existing application which heavily used underscores as part of another library, I ran into a conflict.

I think the best way to fix this is to use es6 symbols, or when symbols are not available, a configurable, namespaced property name like `@@automerge/state`

I'd be happy to propose a pull request, but I think it's best to discuss it a bit first

- are there any objections to this proposal?
- are there any other solutions that may come to mind?
- is the issue encountered by others? What were their solutions?

**Comment by ept** [comment]
Hi @rikkertkoppes, thanks for your proposal. I agree that using ES6 symbols would be a nicer solution than reserving all underscore-prefixed names, and I would happily accept a pull request that does this.

Can the fallback from symbol to a namespaced property be done with reasonably clean code? Also, with this approach, what would the API for getting an object ID or conflicts look like? Would it be something like `Automerge.getConflicts(doc.foo)` instead of `doc.foo._conflicts`, or something else?

**Comment by rikkertkoppes** [comment]
Working on it here: https://github.com/rikkertkoppes/automerge/tree/allow_underscore

Specifically for the fallback, I extracted a map of props here: https://github.com/rikkertkoppes/automerge/blob/allow_underscore/src/prop_names.js

Basically I replace `obj._objectId` with `obj[propNames._OBJECT_ID]` everywhere.

Indeed, for doc.foo._conflicts, we would need an api to replace it. I did not realize this, but this would be a breaking change. The thing is, I do not have much experience with automerge, so not really in a position to judge the impact.

What parts would break if all underscore-properties are removed? I'd like to get a list of that.

Maybe the approach would be to deprecate using the underscore props directly and expose all of them through an api like `Automerge.getConflicts(doc.foo)` This could be a first minor release

The next step (major release as it is a breaking change) is to replace all underscore props. Either with symbols, or with namespaced prop names (such as `@@automerge/objectId`)

I am still trying to find out which underscore props there actually are and what things break if I remove them. I do seem to have some problems with `_init` and `_inbound` when using them as symbols in conjunction with immutability. Still need to dive into that.

**Comment by EthanRBrown** [comment]
Just my $0.02: while I love the _idea_ behind symbols, I have had nothing but headaches trying to use them with real-world code bases.  So I've shied away from them.

But the last time I tried (and had headaches) using symbols was probably a year ago, so maybe things are better now...but I do worry about symbols breaking things.  And I'm not sure what impact (if any) it will have on the Webpack/Babel dist generation....

Let's just say I'll be watching this issue with interest.  @rikkertkoppes, maybe drop me a line when you've got a release candidate, and I'll give it a spin....

**Comment by rikkertkoppes** [comment]
Can you elaborate on the headaches? As much as I value your concern, your comment is not much use to me as I cannot validate your problems would apply to this case.

**Comment by EthanRBrown** [comment]
Ach, I was afraid you were going to ask that.  I'm going off of memory here, but I think the problem cropped up in two places: serialization/persistence and transcompilation.

The serialization/persistence issue may be irrelevant since the serialized Automerge objects don't actually contain `_objectId` et al.

Transompilation is no longer an issue...I just threw a symbol in the source code and transcompiled successfully.  So I guess I'm worried about nothing!  I'm just anxious because I'm relying on Automerge in production, and I want it to keep working!

Given that I'm worried about nothing, I'll reiterate that I think this is a GREAT change.

**Comment by ept** [comment]
I have now implemented this request in #150: underscore-prefixed properties are now allowed, and Automerge's own underscore-prefixed APIs have been moved into the main Automerge function namespace to avoid name clashes.

The concerns about use of symbols seem to be unfounded: we have now been using symbols in the Automerge codebase for some while, and nobody has yet complained about any problems with them.
